package model

// MaintenanceSiteConfig 사이트별 정기점검 기준정보 (기획서 §17)
type MaintenanceSiteConfig struct {
	CustomerID       string
	ShortName        string
	Region           string
	HasKlas          bool
	HasRfid          bool
	InspectionCycle  string // monthly|odd_bimonthly|even_bimonthly|quarterly|semi|yearly
	EntryCategory    string // normal | fixed | office
	FixedRule        string // e.g. LAST_MONDAY_OF_MONTH
	OrgName          string // JOIN customers (목록·엑셀용)
}

// MaintenancePlan 연도 단위 점검 계획
type MaintenancePlan struct {
	PlanID    string
	PlanYear  int
	Title     string
	Status    string // draft | approved
	CreatedAt string
	UpdatedAt string
}

// MaintenanceVisit 일자별 방문 1건
type MaintenanceVisit struct {
	VisitID        string
	PlanID         string
	VisitDate      string // YYYY-MM-DD
	CustomerID     string
	OrgName        string // join
	ShortName      string // join / display
	SortOrder      int
	AutoGenerated  bool
	EntryCategory  string
	Notes          string
	Assignee       string // 점검 담당자
	ProductType    string // KLAS / 앤로보틱스 등 점검 대상 구분
	Completed      bool   // 방문 완료 여부
	CompletedDate  string // 실제 방문일 (미입력 시 예정일)
}

// DoneOn 완료 표시에 쓸 날짜 — 실제 방문일이 없으면 예정일을 쓴다.
func (v MaintenanceVisit) DoneOn() string {
	if v.CompletedDate != "" {
		return v.CompletedDate
	}
	return v.VisitDate
}
