package model

// MaintenanceSiteConfig 사이트별 정기점검 기준정보 (기획서 §17)
type MaintenanceSiteConfig struct {
	CustomerID       string
	ShortName        string
	Region           string
	HasKlas          bool
	HasRfid          bool
	InspectionCycle  string // monthly|odd_bimonthly|even_bimonthly|quarterly|semi|yearly
	EntryCategory    string // normal | fixed | office
	FixedRule        string // e.g. LAST_MONDAY_OF_MONTH
	OrgName          string // JOIN customers (목록·엑셀용)
}

// MaintenancePlan 연도 단위 점검 계획
type MaintenancePlan struct {
	PlanID    string
	PlanYear  int
	Title     string
	Status    string // draft | approved
	CreatedAt string
	UpdatedAt string
}

// MaintenanceVisit 일자별 방문 1건
type MaintenanceVisit struct {
	VisitID        string
	PlanID         string
	VisitDate      string // YYYY-MM-DD
	CustomerID     string
	OrgName        string // join
	ShortName      string // join / display
	SortOrder      int
	AutoGenerated  bool
	EntryCategory  string
	Notes          string
}
