package model

import (
	"fmt"
	"strings"
	"time"
)

// MaintenanceSiteConfig 사이트별 정기점검 기준정보 (기획서 §17)
type MaintenanceSiteConfig struct {
	CustomerID      string
	ShortName       string
	Region          string
	HasKlas         bool
	HasRfid         bool
	InspectionCycle string // monthly|odd_bimonthly|even_bimonthly|quarterly|semi|yearly
	EntryCategory   string // normal | fixed | office
	FixedRule       string // e.g. LAST_MONDAY_OF_MONTH 또는 "5" · "5,15"
	OrgName         string // JOIN customers (목록·엑셀용)
	AddrSido        string // customers.addr_sido
	AddrSigungu     string // customers.addr_sigungu
}

// MaintenancePlan 연도 단위 점검 계획
type MaintenancePlan struct {
	PlanID    string
	PlanYear  int
	Title     string
	Status    string // draft | approved
	CreatedAt string
	UpdatedAt string
}

// MaintenanceVisit 일자별 방문 1건
type MaintenanceVisit struct {
	VisitID       string
	PlanID        string
	VisitDate     string // YYYY-MM-DD
	CustomerID    string
	OrgName       string // join
	ShortName     string // join / display
	SortOrder     int
	AutoGenerated bool
	EntryCategory string
	Notes         string
	Assignee      string // 점검 담당자
	ProductType   string // KLAS / 앤로보틱스 등 점검 대상 구분
	ProjectID     string // 사업(프로젝트)
	ProjectName   string // JOIN work_projects
	Completed     bool   // 방문 완료 여부
	CompletedDate string // 실제 방문일 (미입력 시 예정일)
	DupReason     string
}

// DoneOn 완료 표시에 쓸 날짜 — 실제 방문일이 없으면 예정일을 쓴다.
func (v MaintenanceVisit) DoneOn() string {
	if v.CompletedDate != "" {
		return v.CompletedDate
	}
	return v.VisitDate
}

// UnassignedMonthSlot 이번 달 주기에 해당하지만 방문일이 아직 없는 사이트×점검대상
type UnassignedMonthSlot struct {
	CustomerID  string
	OrgName     string
	ShortName   string
	ProductType string
	SlotKey     string
	Cycle       string
}

// VisitProductSlotKey 방문의 점검대상을 슬롯 키로 정규화한다(klas/rfid/generic).
func VisitProductSlotKey(product string) string {
	raw := strings.TrimSpace(product)
	if raw == "" {
		return "generic"
	}
	compact := strings.ToUpper(raw)
	compact = strings.ReplaceAll(compact, " ", "")
	compact = strings.ReplaceAll(compact, "-", "")
	compact = strings.ReplaceAll(compact, "_", "")
	if strings.Contains(raw, "앤로보") || strings.Contains(compact, "ANROBO") || strings.Contains(compact, "RFID") {
		return "rfid"
	}
	if strings.Contains(compact, "KLAS") {
		return "klas"
	}
	return "generic"
}

// SiteDueProductSlots 그 달 주기가 도래한 사이트의 점검대상 슬롯(표시명 포함).
func SiteDueProductSlots(cfg MaintenanceSiteConfig, month int) []UnassignedMonthSlot {
	if !InspectionCycleDue(cfg.InspectionCycle, month) {
		return nil
	}
	name := cfg.ShortName
	if name == "" {
		name = cfg.OrgName
	}
	base := UnassignedMonthSlot{
		CustomerID: cfg.CustomerID, OrgName: cfg.OrgName, ShortName: name, Cycle: cfg.InspectionCycle,
	}
	var out []UnassignedMonthSlot
	if cfg.HasKlas {
		s := base
		s.ProductType = "KLAS"
		s.SlotKey = "klas"
		out = append(out, s)
	}
	if cfg.HasRfid {
		s := base
		s.ProductType = "앤로보틱스"
		s.SlotKey = "rfid"
		out = append(out, s)
	}
	if len(out) == 0 {
		s := base
		s.ProductType = ""
		s.SlotKey = "generic"
		out = append(out, s)
	}
	return out
}

// MonthPrefix YYYY-MM-
func MonthPrefix(year, month int) string {
	return fmt.Sprintf("%04d-%02d-", year, month)
}

// InspectionCycleDue 점검주기가 해당 월에 도래하는지 (기획서 §17.2).
// 월=매월, 홀수격월=1·3·5·7·9·11, 짝수격월=2·4·6·8·10·12, 분기=1·4·7·10, 반기=1·7, 년1회=1월.
func InspectionCycleDue(cycle string, month int) bool {
	if month < 1 || month > 12 {
		return false
	}
	switch strings.TrimSpace(cycle) {
	case "", "monthly":
		return true
	case "odd_bimonthly":
		return month%2 == 1
	case "even_bimonthly":
		return month%2 == 0
	case "quarterly":
		return month == 1 || month == 4 || month == 7 || month == 10
	case "semi":
		return month == 1 || month == 7
	case "yearly":
		return month == 1
	default:
		return true
	}
}

// NextMonthStart 서버 시각 기준 다음 달 1일 0시.
func NextMonthStart(now time.Time) time.Time {
	loc := now.Location()
	if loc == nil {
		loc = time.Local
	}
	first := time.Date(now.Year(), now.Month(), 1, 0, 0, 0, 0, loc)
	return first.AddDate(0, 1, 0)
}

// VisitDeleteProtected 당월·이전 달 방문은 삭제 불가 (§23.11). 기준은 다음 달 1일.
// 방문일이 비어 있으면 아직 실적이 아니므로 보호하지 않는다(계획 복사 초안).
func VisitDeleteProtected(visitDate string, now time.Time) bool {
	d := strings.TrimSpace(visitDate)
	if d == "" {
		return false
	}
	if len(d) < 10 {
		return true
	}
	return d[:10] < NextMonthStart(now).Format("2006-01-02")
}

// VisitAutoReassignProtected 자동 배정 재생성 보호. 기준은 오늘(당일 포함). §34.4.5
func VisitAutoReassignProtected(visitDate string, now time.Time) bool {
	d := strings.TrimSpace(visitDate)
	if d == "" {
		return false
	}
	if len(d) < 10 {
		return true
	}
	today := now.Format("2006-01-02")
	return d[:10] <= today
}

// ErrGeneratePastMonth 지난 달 자동 배정 거부. §34.4.5
var ErrGeneratePastMonth = fmt.Errorf("지난 달은 배정할 수 없습니다. 이미 지난 일정입니다.")

func IsPastGenerateMonth(year, month int, now time.Time) bool {
	if month < 1 || month > 12 {
		return false
	}
	if year < now.Year() {
		return true
	}
	return year == now.Year() && month < int(now.Month())
}

type VisitStatusBadge struct {
	Kind  string // done | overdue | ""
	Label string
	Class string
	Extra string // 완료일
}

func VisitStatusBadgeOf(v MaintenanceVisit, today string) VisitStatusBadge {
	today = strings.TrimSpace(today)
	if today == "" {
		today = time.Now().Format("2006-01-02")
	}
	if v.Completed {
		return VisitStatusBadge{
			Kind:  "done",
			Label: "방문완료",
			Class: "px-1.5 py-0.5 rounded-full bg-green-100 text-green-800 text-[10px] font-semibold",
			Extra: v.DoneOn(),
		}
	}
	d := strings.TrimSpace(v.VisitDate)
	if len(d) >= 10 && d[:10] < today {
		n := DaysBetweenDates(d[:10], today)
		if n < 1 {
			n = 1
		}
		return VisitStatusBadge{
			Kind:  "overdue",
			Label: fmt.Sprintf("D+%d", n),
			Class: "px-1.5 py-0.5 rounded-full bg-red-100 text-red-800 text-[10px] font-semibold",
		}
	}
	return VisitStatusBadge{}
}

// DatedVisits 방문일이 있는 일정만. 날짜 없는 복사 초안은 캘린더·실적에서 뺀다.
func DatedVisits(list []MaintenanceVisit) []MaintenanceVisit {
	var out []MaintenanceVisit
	for _, v := range list {
		if len(strings.TrimSpace(v.VisitDate)) >= 10 {
			out = append(out, v)
		}
	}
	return out
}

// ProtectedVisitRangeMessage 계획·일괄 삭제 거부 문구 (§23.11).
func ProtectedVisitRangeMessage(now time.Time, count int) string {
	y, m := now.Year(), int(now.Month())
	if m == 12 {
		return fmt.Sprintf("%d년 1~12월 방문 %d건은 삭제할 수 없습니다. %d년 1월 이후만 정리할 수 있습니다.", y, count, y+1)
	}
	if m == 1 {
		return fmt.Sprintf("%d년 1월 방문 %d건은 삭제할 수 없습니다. 2월 이후만 정리할 수 있습니다.", y, count)
	}
	return fmt.Sprintf("%d년 1~%d월 방문 %d건은 삭제할 수 없습니다. %d월 이후만 정리할 수 있습니다.", y, m, count, m+1)
}

// SiteVisitSlotCount 사이트 1곳의 방문 건수. KLAS·RFID 각각 1건, 둘 다 미지정이면 1건.
func SiteVisitSlotCount(cfg MaintenanceSiteConfig) int {
	n := 0
	if cfg.HasKlas {
		n++
	}
	if cfg.HasRfid {
		n++
	}
	if n == 0 {
		return 1
	}
	return n
}

// CycleQuotaRow 이번 달 주기별 사이트·방문 건수
type CycleQuotaRow struct {
	Cycle string
	Label string
	Sites int
	Slots int
}

// MonthVisitQuota 점검 사이트 설정으로 산출한 그 달 방문 목표
type MonthVisitQuota struct {
	Year       int
	Month      int
	MonthLabel string
	DueSites   int
	Slots      int
	KlasSlots  int
	RfidSlots  int
	CycleRows  []CycleQuotaRow
}

var inspectionCycleOrder = []struct{ Key, Label string }{
	{"monthly", "월"},
	{"odd_bimonthly", "홀수격월"},
	{"even_bimonthly", "짝수격월"},
	{"quarterly", "분기"},
	{"semi", "반기"},
	{"yearly", "년1회"},
}

// SummarizeMonthVisitQuota 주기가 도래한 사이트의 방문 건수 합 (사이트×점검대상).
func SummarizeMonthVisitQuota(configs []MaintenanceSiteConfig, year, month int) MonthVisitQuota {
	q := MonthVisitQuota{
		Year:       year,
		Month:      month,
		MonthLabel: fmt.Sprintf("%d년 %d월", year, month),
	}
	cycleSites := map[string]int{}
	cycleSlots := map[string]int{}
	for _, c := range configs {
		if !InspectionCycleDue(c.InspectionCycle, month) {
			continue
		}
		cyc := strings.TrimSpace(c.InspectionCycle)
		if cyc == "" {
			cyc = "monthly"
		}
		q.DueSites++
		n := SiteVisitSlotCount(c)
		q.Slots += n
		if c.HasKlas {
			q.KlasSlots++
		}
		if c.HasRfid {
			q.RfidSlots++
		}
		cycleSites[cyc]++
		cycleSlots[cyc] += n
	}
	for _, spec := range inspectionCycleOrder {
		if cycleSites[spec.Key] == 0 {
			continue
		}
		q.CycleRows = append(q.CycleRows, CycleQuotaRow{
			Cycle: spec.Key, Label: spec.Label,
			Sites: cycleSites[spec.Key], Slots: cycleSlots[spec.Key],
		})
	}
	return q
}

// SlotsForProductKey 업무(제품) 필터에 맞는 월 목표. 세종 K-LAS처럼 설정에 없는 구분은 -1(방문 일정으로 산출).
func (q MonthVisitQuota) SlotsForProductKey(key string) int {
	key = strings.TrimSpace(key)
	if key == "" {
		return q.Slots
	}
	if strings.Contains(key, "세종") {
		return -1
	}
	u := strings.ToUpper(strings.ReplaceAll(strings.ReplaceAll(key, "-", ""), " ", ""))
	if strings.Contains(u, "KLAS") {
		return q.KlasSlots
	}
	if strings.Contains(u, "RFID") || strings.Contains(key, "앤") || strings.Contains(key, "로봇") {
		return q.RfidSlots
	}
	return -1
}
