package repository

import (
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"

	"customer-support/internal/model"
)

type MaintenanceRepo struct {
	db *sql.DB
}

func NewMaintenanceRepo(db *sql.DB) *MaintenanceRepo {
	return &MaintenanceRepo{db: db}
}

func randomID(prefix string) string {
	b := make([]byte, 8)
	_, _ = rand.Read(b)
	return prefix + hex.EncodeToString(b)
}

func (r *MaintenanceRepo) ListPlans() ([]model.MaintenancePlan, error) {
	rows, err := r.db.Query(`
		SELECT plan_id, plan_year, COALESCE(title,''), status,
		       IFNULL(created_at,''), IFNULL(updated_at,'')
		FROM maintenance_plans ORDER BY plan_year DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []model.MaintenancePlan
	for rows.Next() {
		var p model.MaintenancePlan
		if err := rows.Scan(&p.PlanID, &p.PlanYear, &p.Title, &p.Status, &p.CreatedAt, &p.UpdatedAt); err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, rows.Err()
}

func (r *MaintenanceRepo) GetPlan(planID string) (*model.MaintenancePlan, error) {
	var p model.MaintenancePlan
	err := r.db.QueryRow(`
		SELECT plan_id, plan_year, COALESCE(title,''), status,
		       IFNULL(created_at,''), IFNULL(updated_at,'')
		FROM maintenance_plans WHERE plan_id = ?`, planID).
		Scan(&p.PlanID, &p.PlanYear, &p.Title, &p.Status, &p.CreatedAt, &p.UpdatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &p, nil
}

func (r *MaintenanceRepo) GetPlanByYear(year int) (*model.MaintenancePlan, error) {
	var p model.MaintenancePlan
	err := r.db.QueryRow(`
		SELECT plan_id, plan_year, COALESCE(title,''), status,
		       IFNULL(created_at,''), IFNULL(updated_at,'')
		FROM maintenance_plans WHERE plan_year = ?`, year).
		Scan(&p.PlanID, &p.PlanYear, &p.Title, &p.Status, &p.CreatedAt, &p.UpdatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &p, nil
}

func (r *MaintenanceRepo) CreatePlan(year int, title string) (*model.MaintenancePlan, error) {
	existing, err := r.GetPlanByYear(year)
	if err != nil {
		return nil, err
	}
	if existing != nil {
		return nil, fmt.Errorf("%d년 계획이 이미 있습니다", year)
	}
	id := randomID("mpl_")
	_, err = r.db.Exec(`
		INSERT INTO maintenance_plans (plan_id, plan_year, title, status, updated_at)
		VALUES (?, ?, ?, 'draft', CURRENT_TIMESTAMP)`, id, year, title)
	if err != nil {
		return nil, err
	}
	return r.GetPlan(id)
}

func (r *MaintenanceRepo) SetPlanStatus(planID, status string) error {
	_, err := r.db.Exec(`UPDATE maintenance_plans SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE plan_id = ?`, status, planID)
	return err
}

func (r *MaintenanceRepo) DeletePlan(planID string) error {
	tx, err := r.db.Begin()
	if err != nil {
		return err
	}
	if _, err := tx.Exec(`DELETE FROM maintenance_visits WHERE plan_id = ?`, planID); err != nil {
		_ = tx.Rollback()
		return err
	}
	if _, err := tx.Exec(`DELETE FROM maintenance_plans WHERE plan_id = ?`, planID); err != nil {
		_ = tx.Rollback()
		return err
	}
	return tx.Commit()
}

func (r *MaintenanceRepo) ListVisits(planID string) ([]model.MaintenanceVisit, error) {
	rows, err := r.db.Query(`
		SELECT v.visit_id, v.plan_id, v.visit_date, v.customer_id,
		       COALESCE(c.org_name,''), COALESCE(cfg.short_name, c.org_name),
		       v.sort_order, v.auto_generated, v.entry_category, COALESCE(v.notes,'')
		FROM maintenance_visits v
		JOIN customers c ON c.customer_id = v.customer_id
		LEFT JOIN maintenance_site_config cfg ON cfg.customer_id = v.customer_id
		WHERE v.plan_id = ?
		ORDER BY v.visit_date, v.sort_order, cfg.short_name`, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanVisits(rows)
}

func scanVisits(rows *sql.Rows) ([]model.MaintenanceVisit, error) {
	var out []model.MaintenanceVisit
	for rows.Next() {
		var v model.MaintenanceVisit
		var auto int
		if err := rows.Scan(&v.VisitID, &v.PlanID, &v.VisitDate, &v.CustomerID,
			&v.OrgName, &v.ShortName, &v.SortOrder, &auto, &v.EntryCategory, &v.Notes); err != nil {
			return nil, err
		}
		v.AutoGenerated = auto == 1
		out = append(out, v)
	}
	return out, rows.Err()
}

func (r *MaintenanceRepo) ListVisitsByMonth(planID string, year, month int) ([]model.MaintenanceVisit, error) {
	prefix := fmt.Sprintf("%d-%02d-%%", year, month)
	rows, err := r.db.Query(`
		SELECT v.visit_id, v.plan_id, v.visit_date, v.customer_id,
		       COALESCE(c.org_name,''), COALESCE(cfg.short_name, c.org_name),
		       v.sort_order, v.auto_generated, v.entry_category, COALESCE(v.notes,'')
		FROM maintenance_visits v
		JOIN customers c ON c.customer_id = v.customer_id
		LEFT JOIN maintenance_site_config cfg ON cfg.customer_id = v.customer_id
		WHERE v.plan_id = ? AND v.visit_date LIKE ?
		ORDER BY v.visit_date, v.sort_order`, planID, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanVisits(rows)
}

func (r *MaintenanceRepo) DeleteAutoVisits(planID string) error {
	_, err := r.db.Exec(`DELETE FROM maintenance_visits WHERE plan_id = ? AND auto_generated = 1`, planID)
	return err
}

func (r *MaintenanceRepo) InsertVisit(planID, visitDate, customerID string, sortOrder, autoGen int, entryCategory, notes string) error {
	id := randomID("mvs_")
	_, err := r.db.Exec(`
		INSERT INTO maintenance_visits
		(visit_id, plan_id, visit_date, customer_id, sort_order, auto_generated, entry_category, notes)
		VALUES (?,?,?,?,?,?,?,?)`,
		id, planID, visitDate, customerID, sortOrder, autoGen, entryCategory, nullIfEmpty(notes))
	return err
}

func nullIfEmpty(s string) interface{} {
	if s == "" {
		return nil
	}
	return s
}

func (r *MaintenanceRepo) DeleteVisit(visitID string) error {
	_, err := r.db.Exec(`DELETE FROM maintenance_visits WHERE visit_id = ?`, visitID)
	return err
}

func (r *MaintenanceRepo) ListSiteConfigs() ([]model.MaintenanceSiteConfig, error) {
	rows, err := r.db.Query(`
		SELECT customer_id, short_name, COALESCE(region,''),
		       has_klas, has_rfid, entry_category, COALESCE(fixed_rule,'')
		FROM maintenance_site_config ORDER BY region, short_name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []model.MaintenanceSiteConfig
	for rows.Next() {
		var c model.MaintenanceSiteConfig
		var klas, rfid int
		if err := rows.Scan(&c.CustomerID, &c.ShortName, &c.Region, &klas, &rfid, &c.EntryCategory, &c.FixedRule); err != nil {
			return nil, err
		}
		c.HasKlas = klas == 1
		c.HasRfid = rfid == 1
		out = append(out, c)
	}
	return out, rows.Err()
}

func (r *MaintenanceRepo) GetSiteConfig(customerID string) (*model.MaintenanceSiteConfig, error) {
	var c model.MaintenanceSiteConfig
	var klas, rfid int
	err := r.db.QueryRow(`
		SELECT customer_id, short_name, COALESCE(region,''),
		       has_klas, has_rfid, entry_category, COALESCE(fixed_rule,'')
		FROM maintenance_site_config WHERE customer_id = ?`, customerID).
		Scan(&c.CustomerID, &c.ShortName, &c.Region, &klas, &rfid, &c.EntryCategory, &c.FixedRule)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	c.HasKlas = klas == 1
	c.HasRfid = rfid == 1
	return &c, nil
}

func (r *MaintenanceRepo) UpsertSiteConfig(c *model.MaintenanceSiteConfig) error {
	klas, rfid := 0, 0
	if c.HasKlas {
		klas = 1
	}
	if c.HasRfid {
		rfid = 1
	}
	res, err := r.db.Exec(`
		UPDATE maintenance_site_config SET
			short_name = ?, region = ?, has_klas = ?, has_rfid = ?,
			entry_category = ?, fixed_rule = ?, updated_at = CURRENT_TIMESTAMP
		WHERE customer_id = ?`,
		c.ShortName, c.Region, klas, rfid, c.EntryCategory, nullString(c.FixedRule), c.CustomerID)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n > 0 {
		return nil
	}
	_, err = r.db.Exec(`
		INSERT INTO maintenance_site_config
		(customer_id, short_name, region, has_klas, has_rfid, entry_category, fixed_rule, updated_at)
		VALUES (?,?,?,?,?,?,?, CURRENT_TIMESTAMP)`,
		c.CustomerID, c.ShortName, c.Region, klas, rfid, c.EntryCategory, nullString(c.FixedRule))
	return err
}

func nullString(s string) interface{} {
	if s == "" {
		return nil
	}
	return s
}

func (r *MaintenanceRepo) DeleteSiteConfig(customerID string) error {
	_, err := r.db.Exec(`DELETE FROM maintenance_site_config WHERE customer_id = ?`, customerID)
	return err
}

// ListCustomersWithoutConfig 점검 설정이 없는 활성 고객 (선택용)
func (r *MaintenanceRepo) ListCustomersWithoutConfig() ([]struct{ ID, OrgName string }, error) {
	rows, err := r.db.Query(`
		SELECT c.customer_id, c.org_name FROM customers c
		WHERE c.is_active = 1 AND NOT EXISTS (
			SELECT 1 FROM maintenance_site_config s WHERE s.customer_id = c.customer_id
		) ORDER BY c.org_name LIMIT 500`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []struct{ ID, OrgName string }
	for rows.Next() {
		var id, name string
		if err := rows.Scan(&id, &name); err != nil {
			return nil, err
		}
		out = append(out, struct{ ID, OrgName string }{id, name})
	}
	return out, rows.Err()
}

// TouchPlanUpdated 계획 수정 시각
func (r *MaintenanceRepo) TouchPlanUpdated(planID string) {
	_, _ = r.db.Exec(`UPDATE maintenance_plans SET updated_at = CURRENT_TIMESTAMP WHERE plan_id = ?`, planID)
}
