package repository

import (
	"path/filepath"
	"testing"
	"time"

	"customer-support/internal/model"
)

func TestListUnassignedMonthSlotsAndAssign(t *testing.T) {
	dir := t.TempDir()
	db, err := InitDB(filepath.Join(dir, "unassigned.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
		VALUES ('c1','가나도서관','가나도서관',1)`); err != nil {
		t.Fatal(err)
	}
	repo := NewMaintenanceRepo(db)
	if err := repo.UpsertSiteConfig(&model.MaintenanceSiteConfig{
		CustomerID: "c1", ShortName: "가나", HasKlas: true, HasRfid: true, InspectionCycle: "monthly",
	}); err != nil {
		t.Fatal(err)
	}
	p, err := repo.CreatePlan(2026, "t")
	if err != nil {
		t.Fatal(err)
	}
	slots, err := repo.ListUnassignedMonthSlots(p.PlanID, 2026, 8)
	if err != nil {
		t.Fatal(err)
	}
	if len(slots) != 2 {
		t.Fatalf("미배정=%d want 2 (KLAS+RFID)", len(slots))
	}

	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-08-10", CustomerID: "c1", ProductType: "KLAS",
	}); err != nil {
		t.Fatal(err)
	}
	slots, err = repo.ListUnassignedMonthSlots(p.PlanID, 2026, 8)
	if err != nil {
		t.Fatal(err)
	}
	if len(slots) != 1 || slots[0].SlotKey != "rfid" {
		t.Fatalf("KLAS 배정 후 미배정=%v", slots)
	}
}

func TestCollapseDuplicateMonthVisitsKeepsOne(t *testing.T) {
	dir := t.TempDir()
	db, err := InitDB(filepath.Join(dir, "dedup.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
		VALUES ('c1','가나도서관','가나도서관',1)`); err != nil {
		t.Fatal(err)
	}
	repo := NewMaintenanceRepo(db)
	repo.Now = func() time.Time { return time.Date(2026, 6, 1, 0, 0, 0, 0, time.Local) }
	p, err := repo.CreatePlan(2026, "t")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-08-10", CustomerID: "c1", ProductType: "KLAS", AutoGenerated: true,
	}); err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-08-14", CustomerID: "c1", ProductType: "KLAS",
	}); err != nil {
		t.Fatal(err)
	}
	n, skipped, err := repo.CollapseDuplicateMonthVisits(p.PlanID, 2026, 8)
	if err != nil {
		t.Fatal(err)
	}
	if n != 1 {
		t.Fatalf("removed=%d skipped=%d want 1", n, skipped)
	}
	list, err := repo.ListVisitsByMonth(p.PlanID, 2026, 8)
	if err != nil || len(list) != 1 {
		t.Fatalf("남은 건=%d err=%v", len(list), err)
	}
	if list[0].VisitDate != "2026-08-14" {
		t.Fatalf("남은 날짜=%s want 2026-08-14", list[0].VisitDate)
	}
}

func TestUpdateVisitMovesDateAndProject(t *testing.T) {
	dir := t.TempDir()
	db, err := InitDB(filepath.Join(dir, "move.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
		VALUES ('c1','가나도서관','가나도서관',1)`); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`INSERT INTO work_projects (project_id, name, short_name, plan_year, is_paid, sort_order, status)
		VALUES ('WP1','도서관 유지보수','유지보수',2026,1,1,'active')`); err != nil {
		t.Fatal(err)
	}
	repo := NewMaintenanceRepo(db)
	p, err := repo.CreatePlan(2026, "t")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-08-10", CustomerID: "c1", ProductType: "KLAS",
	}); err != nil {
		t.Fatal(err)
	}
	visits, _ := repo.ListVisits(p.PlanID)
	v := visits[0]
	v.VisitDate = "2026-08-14"
	v.ProjectID = "WP1"
	if err := repo.UpdateVisit(v); err != nil {
		t.Fatal(err)
	}
	got, err := repo.GetVisit(v.VisitID)
	if err != nil {
		t.Fatal(err)
	}
	if got.VisitDate != "2026-08-14" {
		t.Fatalf("date=%s", got.VisitDate)
	}
	if got.ProjectID != "WP1" || got.ProjectName == "" {
		t.Fatalf("project=%s name=%s", got.ProjectID, got.ProjectName)
	}
	aug10 := filterByDate(visitsAfter(t, repo, p.PlanID), "2026-08-10")
	if len(aug10) != 0 {
		t.Fatalf("옛 날짜에 남음: %d", len(aug10))
	}
}

func visitsAfter(t *testing.T, repo *MaintenanceRepo, planID string) []model.MaintenanceVisit {
	t.Helper()
	list, err := repo.ListVisits(planID)
	if err != nil {
		t.Fatal(err)
	}
	return list
}

func filterByDate(list []model.MaintenanceVisit, date string) []model.MaintenanceVisit {
	var out []model.MaintenanceVisit
	for _, v := range list {
		if v.VisitDate == date {
			out = append(out, v)
		}
	}
	return out
}
