package repository

import (
	"errors"
	"fmt"
	"strings"

	"customer-support/internal/model"
)

// ErrVisitDeleteProtected 당월·이전 달 방문 삭제 거부 (§23.11).
var ErrVisitDeleteProtected = fmt.Errorf("당월·이전 달 방문은 삭제할 수 없습니다")

// DuplicateDrop 중복 정리 시 지워질 방문과 남을 방문.
type DuplicateDrop struct {
	Drop      model.MaintenanceVisit
	Keep      model.MaintenanceVisit
	Protected bool
}

// GuardPlanDelete 계획 삭제 가능 여부를 검사한다. 핸들러가 백업 전에 호출한다.
func (r *MaintenanceRepo) GuardPlanDelete(planID string) error {
	return r.guardPlanDelete(planID)
}

func (r *MaintenanceRepo) guardPlanDelete(planID string) error {
	plan, err := r.GetPlan(planID)
	if err != nil || plan == nil {
		return fmt.Errorf("계획을 찾을 수 없습니다")
	}
	now := r.nowTime()
	if plan.PlanYear < now.Year() {
		return fmt.Errorf("%d년 계획은 삭제할 수 없습니다. 보관으로만 내릴 수 있습니다", plan.PlanYear)
	}
	st, err := r.PlanDeleteStats(planID)
	if err != nil {
		return err
	}
	if st.Completed > 0 {
		return fmt.Errorf("완료된 방문 %d건이 있어 계획을 삭제할 수 없습니다. 먼저 보관 상태로 바꾸세요", st.Completed)
	}
	if st.Protected > 0 {
		return fmt.Errorf("%s", model.ProtectedVisitRangeMessage(now, st.Protected))
	}
	return nil
}

// PlanDeleteStats 계획 삭제 영향 범위.
type PlanDeleteStats struct {
	Total     int
	Completed int
	Protected int
}

func (r *MaintenanceRepo) PlanDeleteStats(planID string) (PlanDeleteStats, error) {
	visits, err := r.ListVisits(planID)
	if err != nil {
		return PlanDeleteStats{}, err
	}
	now := r.nowTime()
	var st PlanDeleteStats
	st.Total = len(visits)
	for _, v := range visits {
		if v.Completed {
			st.Completed++
		}
		if model.VisitDeleteProtected(v.VisitDate, now) {
			st.Protected++
		}
	}
	return st, nil
}

func (r *MaintenanceRepo) AutoVisitDeleteStats(planID string) (deletable, protected int, err error) {
	visits, err := r.ListVisits(planID)
	if err != nil {
		return 0, 0, err
	}
	now := r.nowTime()
	for _, v := range visits {
		if !v.AutoGenerated {
			continue
		}
		if v.Completed || model.VisitDeleteProtected(v.VisitDate, now) {
			protected++
			continue
		}
		deletable++
	}
	return deletable, protected, nil
}

func (r *MaintenanceRepo) ListDuplicateDrops(planID string, year, month int) ([]DuplicateDrop, error) {
	visits, err := r.ListVisitsByMonth(planID, year, month)
	if err != nil {
		return nil, err
	}
	type key struct{ cust, slot string }
	best := map[key]model.MaintenanceVisit{}
	var drops []DuplicateDrop
	for _, v := range visits {
		k := key{v.CustomerID, model.VisitProductSlotKey(v.ProductType)}
		cur, ok := best[k]
		if !ok {
			best[k] = v
			continue
		}
		keep, lose := pickBetterMonthVisit(cur, v)
		best[k] = keep
		drops = append(drops, DuplicateDrop{Drop: lose, Keep: keep})
	}
	for _, v := range visits {
		if model.VisitProductSlotKey(v.ProductType) != "generic" {
			continue
		}
		_, hasKlas := best[key{v.CustomerID, "klas"}]
		_, hasRfid := best[key{v.CustomerID, "rfid"}]
		if hasKlas || hasRfid {
			keep := best[key{v.CustomerID, "klas"}]
			if keep.VisitID == "" {
				keep = best[key{v.CustomerID, "rfid"}]
			}
			drops = append(drops, DuplicateDrop{Drop: v, Keep: keep})
			delete(best, key{v.CustomerID, "generic"})
		}
	}
	now := r.nowTime()
	seen := map[string]struct{}{}
	kept := map[string]struct{}{}
	for _, v := range best {
		kept[v.VisitID] = struct{}{}
	}
	var out []DuplicateDrop
	for _, d := range drops {
		if d.Drop.VisitID == "" {
			continue
		}
		if _, ok := seen[d.Drop.VisitID]; ok {
			continue
		}
		if _, ok := kept[d.Drop.VisitID]; ok {
			continue
		}
		seen[d.Drop.VisitID] = struct{}{}
		d.Protected = model.VisitDeleteProtected(d.Drop.VisitDate, now)
		out = append(out, d)
	}
	return out, nil
}

func (r *MaintenanceRepo) CountDuplicateDrops(planID string, year int, month int) (int, error) {
	if month >= 1 && month <= 12 {
		d, err := r.ListDuplicateDrops(planID, year, month)
		return len(d), err
	}
	n := 0
	for m := 1; m <= 12; m++ {
		d, err := r.ListDuplicateDrops(planID, year, m)
		if err != nil {
			return n, err
		}
		n += len(d)
	}
	return n, nil
}

// DeleteVisitIDs 기간 보호 대상은 건너뛰고 나머지만 지운다. skipped 는 제외 건수.
func (r *MaintenanceRepo) DeleteVisitIDs(ids []string) (deleted, skipped int, err error) {
	now := r.nowTime()
	for _, id := range ids {
		id = strings.TrimSpace(id)
		if id == "" {
			continue
		}
		v, getErr := r.GetVisit(id)
		if getErr != nil || v == nil {
			skipped++
			continue
		}
		if model.VisitDeleteProtected(v.VisitDate, now) {
			skipped++
			continue
		}
		if delErr := r.DeleteVisit(id); delErr != nil {
			if errors.Is(delErr, ErrVisitDeleteProtected) {
				skipped++
				continue
			}
			return deleted, skipped, delErr
		}
		deleted++
	}
	return deleted, skipped, nil
}
