package repository

import (
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"customer-support/internal/model"
)

type MaintenanceRepo struct {
	db  *sql.DB
	Now func() time.Time // 테스트용 시계. nil 이면 time.Now
}

func NewMaintenanceRepo(db *sql.DB) *MaintenanceRepo {
	return &MaintenanceRepo{db: db}
}

func randomID(prefix string) string {
	b := make([]byte, 8)
	_, _ = rand.Read(b)
	return prefix + hex.EncodeToString(b)
}

func (r *MaintenanceRepo) ListPlans() ([]model.MaintenancePlan, error) {
	rows, err := r.db.Query(`
		SELECT plan_id, plan_year, COALESCE(title,''), status,
		       IFNULL(created_at,''), IFNULL(updated_at,'')
		FROM maintenance_plans ORDER BY plan_year DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []model.MaintenancePlan
	for rows.Next() {
		var p model.MaintenancePlan
		if err := rows.Scan(&p.PlanID, &p.PlanYear, &p.Title, &p.Status, &p.CreatedAt, &p.UpdatedAt); err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, rows.Err()
}

func (r *MaintenanceRepo) GetPlan(planID string) (*model.MaintenancePlan, error) {
	var p model.MaintenancePlan
	err := r.db.QueryRow(`
		SELECT plan_id, plan_year, COALESCE(title,''), status,
		       IFNULL(created_at,''), IFNULL(updated_at,'')
		FROM maintenance_plans WHERE plan_id = ?`, planID).
		Scan(&p.PlanID, &p.PlanYear, &p.Title, &p.Status, &p.CreatedAt, &p.UpdatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &p, nil
}

func (r *MaintenanceRepo) GetPlanByYear(year int) (*model.MaintenancePlan, error) {
	var p model.MaintenancePlan
	err := r.db.QueryRow(`
		SELECT plan_id, plan_year, COALESCE(title,''), status,
		       IFNULL(created_at,''), IFNULL(updated_at,'')
		FROM maintenance_plans WHERE plan_year = ?`, year).
		Scan(&p.PlanID, &p.PlanYear, &p.Title, &p.Status, &p.CreatedAt, &p.UpdatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &p, nil
}

func (r *MaintenanceRepo) CreatePlan(year int, title string) (*model.MaintenancePlan, error) {
	existing, err := r.GetPlanByYear(year)
	if err != nil {
		return nil, err
	}
	if existing != nil {
		return nil, fmt.Errorf("%d년 계획이 이미 있습니다", year)
	}
	id := randomID("mpl_")
	_, err = r.db.Exec(`
		INSERT INTO maintenance_plans (plan_id, plan_year, title, status, updated_at)
		VALUES (?, ?, ?, 'draft', CURRENT_TIMESTAMP)`, id, year, title)
	if err != nil {
		return nil, err
	}
	return r.GetPlan(id)
}

func (r *MaintenanceRepo) SetPlanStatus(planID, status string) error {
	switch status {
	case "draft", "approved", "archived":
	default:
		return fmt.Errorf("상태 값이 올바르지 않습니다")
	}
	_, err := r.db.Exec(`UPDATE maintenance_plans SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE plan_id = ?`, status, planID)
	return err
}

func (r *MaintenanceRepo) nowTime() time.Time {
	if r != nil && r.Now != nil {
		return r.Now()
	}
	return time.Now()
}

func (r *MaintenanceRepo) DeletePlan(planID string) error {
	if err := r.guardPlanDelete(planID); err != nil {
		return err
	}
	if err := r.deleteVisitsLogged(`plan_id = ?`, planID); err != nil {
		return err
	}
	_, err := r.db.Exec(`DELETE FROM maintenance_plans WHERE plan_id = ?`, planID)
	return err
}

// visitSelectColumns 방문 목록 공통 컬럼 (scanVisits와 순서를 맞춘다)
const visitSelectColumns = `
		SELECT v.visit_id, v.plan_id, v.visit_date, v.customer_id,
		       COALESCE(c.org_name,''), COALESCE(cfg.short_name, c.org_name),
		       v.sort_order, v.auto_generated, v.entry_category, COALESCE(v.notes,''),
		       COALESCE(v.assignee,''), COALESCE(v.product_type,''),
		       COALESCE(v.completed,0), COALESCE(v.completed_date,''),
		       COALESCE(v.project_id,''), COALESCE(p.name,'')
		FROM maintenance_visits v
		JOIN customers c ON c.customer_id = v.customer_id
		LEFT JOIN maintenance_site_config cfg ON cfg.customer_id = v.customer_id
		LEFT JOIN work_projects p ON p.project_id = v.project_id`

func (r *MaintenanceRepo) ListVisits(planID string) ([]model.MaintenanceVisit, error) {
	rows, err := r.db.Query(visitSelectColumns+`
		WHERE v.plan_id = ?
		ORDER BY v.visit_date, v.sort_order, cfg.short_name`, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanVisits(rows)
}

func scanVisits(rows *sql.Rows) ([]model.MaintenanceVisit, error) {
	var out []model.MaintenanceVisit
	for rows.Next() {
		var v model.MaintenanceVisit
		var auto, completed int
		if err := rows.Scan(&v.VisitID, &v.PlanID, &v.VisitDate, &v.CustomerID,
			&v.OrgName, &v.ShortName, &v.SortOrder, &auto, &v.EntryCategory, &v.Notes,
			&v.Assignee, &v.ProductType, &completed, &v.CompletedDate,
			&v.ProjectID, &v.ProjectName); err != nil {
			return nil, err
		}
		v.AutoGenerated = auto == 1
		v.Completed = completed == 1
		out = append(out, v)
	}
	return out, rows.Err()
}

func (r *MaintenanceRepo) ListVisitsByMonth(planID string, year, month int) ([]model.MaintenanceVisit, error) {
	prefix := fmt.Sprintf("%d-%02d-%%", year, month)
	rows, err := r.db.Query(visitSelectColumns+`
		WHERE v.plan_id = ? AND v.visit_date LIKE ?
		ORDER BY v.visit_date, v.sort_order`, planID, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanVisits(rows)
}

// ListVisitsBetween 기간 안의 모든 계획 방문 (업무 등록 화면의 정기점검 카드용)
func (r *MaintenanceRepo) ListVisitsBetween(from, to string) ([]model.MaintenanceVisit, error) {
	rows, err := r.db.Query(visitSelectColumns+`
		WHERE v.visit_date >= ? AND v.visit_date <= ?
		ORDER BY v.visit_date, v.sort_order`, from, to)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanVisits(rows)
}

// GetVisit 방문 1건
func (r *MaintenanceRepo) GetVisit(visitID string) (*model.MaintenanceVisit, error) {
	rows, err := r.db.Query(visitSelectColumns+` WHERE v.visit_id=?`, visitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	list, err := scanVisits(rows)
	if err != nil || len(list) == 0 {
		return nil, err
	}
	v := list[0]
	return &v, nil
}

func (r *MaintenanceRepo) DeleteAutoVisits(planID string) (deleted, skipped int, err error) {
	return r.deleteAutoVisitsFiltered(planID, "", false)
}

// DeleteAutoVisitsInMonth 그 달의 오늘 이후 미완료 자동생성분만 지운다. §34.4.5
func (r *MaintenanceRepo) DeleteAutoVisitsInMonth(planID string, year, month int) (deleted, skipped int, err error) {
	return r.deleteAutoVisitsFiltered(planID, model.MonthPrefix(year, month), true)
}

func (r *MaintenanceRepo) deleteAutoVisitsFiltered(planID, monthPrefix string, useTodayProtect bool) (deleted, skipped int, err error) {
	q := `SELECT visit_id, visit_date, COALESCE(completed,0) FROM maintenance_visits WHERE plan_id = ? AND auto_generated = 1`
	args := []interface{}{planID}
	if monthPrefix != "" {
		q += ` AND visit_date LIKE ?`
		args = append(args, monthPrefix+"%")
	}
	rows, err := r.db.Query(q, args...)
	if err != nil {
		return 0, 0, err
	}
	type row struct {
		id, date string
		done     int
	}
	var list []row
	for rows.Next() {
		var x row
		if err := rows.Scan(&x.id, &x.date, &x.done); err != nil {
			rows.Close()
			return 0, 0, err
		}
		list = append(list, x)
	}
	rows.Close()
	now := r.nowTime()
	for _, x := range list {
		protect := model.VisitDeleteProtected(x.date, now)
		if useTodayProtect {
			protect = model.VisitAutoReassignProtected(x.date, now)
		}
		if x.done == 1 || protect {
			skipped++
			continue
		}
		var err error
		if useTodayProtect {
			err = r.removeVisitRow(x.id)
		} else {
			err = r.DeleteVisit(x.id)
		}
		if err != nil {
			if errors.Is(err, ErrVisitDeleteProtected) {
				skipped++
				continue
			}
			return deleted, skipped, err
		}
		deleted++
	}
	return deleted, skipped, nil
}

func (r *MaintenanceRepo) deleteVisitsLogged(where string, args ...interface{}) error {
	rows, err := r.db.Query(`SELECT visit_id FROM maintenance_visits WHERE `+where, args...)
	if err != nil {
		return err
	}
	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return err
		}
		ids = append(ids, id)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}
	for _, id := range ids {
		if err := r.DeleteVisit(id); err != nil {
			return err
		}
	}
	return nil
}

func (r *MaintenanceRepo) InsertVisit(planID, visitDate, customerID string, sortOrder, autoGen int, entryCategory, notes string) error {
	return r.InsertVisitFull(model.MaintenanceVisit{
		PlanID: planID, VisitDate: visitDate, CustomerID: customerID,
		SortOrder: sortOrder, AutoGenerated: autoGen == 1,
		EntryCategory: entryCategory, Notes: notes,
	})
}

// InsertVisitFull 담당자·점검대상·완료여부까지 지정해 방문을 넣는다.
func (r *MaintenanceRepo) InsertVisitFull(v model.MaintenanceVisit) error {
	id := v.VisitID
	if id == "" {
		id = randomID("mvs_")
	}
	auto := 0
	if v.AutoGenerated {
		auto = 1
	}
	completed := 0
	completedDate := ""
	if v.Completed {
		completed = 1
		completedDate = v.DoneOn()
	}
	if v.EntryCategory == "" {
		v.EntryCategory = "normal"
	}
	if strings.TrimSpace(v.ProjectID) == "" {
		v.ProjectID = resolveStoredProjectID(r.db, v.CustomerID, v.ProductType, model.ScopeWorkMaintenance)
	}
	_, err := r.db.Exec(`
		INSERT INTO maintenance_visits
		(visit_id, plan_id, visit_date, customer_id, sort_order, auto_generated, entry_category, notes,
		 assignee, product_type, completed, completed_date, project_id)
		VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
		id, v.PlanID, v.VisitDate, v.CustomerID, v.SortOrder, auto, v.EntryCategory, nullIfEmpty(v.Notes),
		nullIfEmpty(v.Assignee), nullIfEmpty(v.ProductType), completed, nullIfEmpty(completedDate),
		nullIfEmpty(v.ProjectID))
	return err
}

// UpdateVisit 방문 일정·담당자·점검대상 등을 수정한다.
func (r *MaintenanceRepo) UpdateVisit(v model.MaintenanceVisit) error {
	if v.VisitID == "" {
		return fmt.Errorf("방문 ID가 없습니다")
	}
	if v.VisitDate == "" || v.CustomerID == "" {
		return fmt.Errorf("날짜와 고객을 선택하세요")
	}
	if v.EntryCategory == "" {
		v.EntryCategory = "normal"
	}
	completed := 0
	completedDate := ""
	if v.Completed {
		completed = 1
		completedDate = v.DoneOn()
	}
	if err := r.clearVisitSlotConflict(v.PlanID, v.VisitDate, v.CustomerID, v.ProductType, v.VisitID); err != nil {
		return err
	}
	if strings.TrimSpace(v.ProjectID) == "" {
		v.ProjectID = resolveStoredProjectID(r.db, v.CustomerID, v.ProductType, model.ScopeWorkMaintenance)
	}
	before := rowJSON(r.db, "maintenance_visits", "visit_id", v.VisitID)
	res, err := r.db.Exec(`
		UPDATE maintenance_visits SET
			visit_date=?, customer_id=?, entry_category=?, notes=?,
			assignee=?, product_type=?, completed=?, completed_date=?, project_id=?
		WHERE visit_id=?`,
		v.VisitDate, v.CustomerID, v.EntryCategory, nullIfEmpty(v.Notes),
		nullIfEmpty(v.Assignee), nullIfEmpty(v.ProductType),
		completed, nullIfEmpty(completedDate), nullIfEmpty(v.ProjectID), v.VisitID)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("방문을 찾을 수 없습니다")
	}
	logUpdate(r.db, "maintenance_visits", "visit_id", v.VisitID, v.VisitDate, before)
	return nil
}

// clearVisitSlotConflict 옮기려는 날짜에 같은 기관·점검대상이 있으면 그 건(다른 ID)을 지워 1건만 남긴다.
func (r *MaintenanceRepo) clearVisitSlotConflict(planID, visitDate, customerID, product, keepID string) error {
	planID = strings.TrimSpace(planID)
	visitDate = strings.TrimSpace(visitDate)
	customerID = strings.TrimSpace(customerID)
	keepID = strings.TrimSpace(keepID)
	if planID == "" || visitDate == "" || customerID == "" || keepID == "" {
		return nil
	}
	rows, err := r.db.Query(`
		SELECT visit_id FROM maintenance_visits
		WHERE plan_id=? AND visit_date=? AND customer_id=?
		  AND COALESCE(product_type,'') = COALESCE(?, '')
		  AND visit_id != ?`,
		planID, visitDate, customerID, strings.TrimSpace(product), keepID)
	if err != nil {
		return err
	}
	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return err
		}
		ids = append(ids, id)
	}
	rows.Close()
	for _, id := range ids {
		if err := r.DeleteVisit(id); err != nil {
			if err == ErrVisitDeleteProtected {
				return fmt.Errorf("당월·이전 달 방문과 겹쳐 옮길 수 없습니다")
			}
			return err
		}
	}
	return nil
}

// CollapseDuplicateMonthVisits 같은 달·같은 기관·같은 점검대상은 1건만 남긴다.
// 완료 건·점검대상이 있는 건·늦은 방문일을 우선한다. 빈 점검대상은 제품 건이 있으면 제거한다.
func (r *MaintenanceRepo) CollapseDuplicateMonthVisits(planID string, year, month int) (deleted, skipped int, err error) {
	drops, err := r.ListDuplicateDrops(planID, year, month)
	if err != nil {
		return 0, 0, err
	}
	var ids []string
	for _, d := range drops {
		ids = append(ids, d.Drop.VisitID)
	}
	deleted, skipped, err = r.DeleteVisitIDs(ids)
	return deleted, skipped, err
}

func pickBetterMonthVisit(a, b model.MaintenanceVisit) (keep, lose model.MaintenanceVisit) {
	score := func(v model.MaintenanceVisit) int {
		s := 0
		if v.Completed {
			s += 100
		}
		if strings.TrimSpace(v.ProductType) != "" {
			s += 10
		}
		if !v.AutoGenerated {
			s += 5
		}
		s += len(v.VisitDate)
		return s
	}
	if score(b) > score(a) || (score(b) == score(a) && b.VisitDate > a.VisitDate) {
		return b, a
	}
	return a, b
}

// ListUnassignedMonthSlots 주기는 도래했는데 그 달에 방문 일정이 없는 사이트×점검대상.
func (r *MaintenanceRepo) ListUnassignedMonthSlots(planID string, year, month int) ([]model.UnassignedMonthSlot, error) {
	configs, err := r.ListSiteConfigs()
	if err != nil {
		return nil, err
	}
	visits, err := r.ListVisitsByMonth(planID, year, month)
	if err != nil {
		return nil, err
	}
	covered := map[string]map[string]bool{} // customer -> slotKey
	for _, v := range visits {
		if covered[v.CustomerID] == nil {
			covered[v.CustomerID] = map[string]bool{}
		}
		covered[v.CustomerID][model.VisitProductSlotKey(v.ProductType)] = true
	}
	var out []model.UnassignedMonthSlot
	for _, cfg := range configs {
		slots := model.SiteDueProductSlots(cfg, month)
		have := covered[cfg.CustomerID]
		genericUsed := have["generic"]
		for _, s := range slots {
			if have[s.SlotKey] {
				continue
			}
			if genericUsed && s.SlotKey != "generic" {
				genericUsed = false
				continue
			}
			out = append(out, s)
		}
	}
	return out, nil
}

// AutoGenerateDailyLimit 자동 초안 하루 배치 상한. 설정이 없거나 잘못되면 4.
func (r *MaintenanceRepo) AutoGenerateDailyLimit() int {
	var v string
	err := r.db.QueryRow(`SELECT setting_value FROM app_settings WHERE setting_key=?`,
		SettingMaintenanceAutoDailyLimit).Scan(&v)
	if err != nil {
		return DefaultMaintenanceAutoDailyLimit
	}
	n, convErr := strconv.Atoi(strings.TrimSpace(v))
	if convErr != nil || n < 1 {
		return DefaultMaintenanceAutoDailyLimit
	}
	return n
}

// HasVisitInMonth 해당 달·기관(·점검대상)에 방문이 있는지.
// product 가 있으면 슬롯 키(klas/rfid/generic)로 대상별로 판정한다.
func (r *MaintenanceRepo) HasVisitInMonth(planID, customerID string, year, month int, product string) bool {
	prefix := model.MonthPrefix(year, month) + "%"
	rows, err := r.db.Query(`
		SELECT COALESCE(product_type,'') FROM maintenance_visits
		WHERE plan_id=? AND customer_id=? AND visit_date LIKE ?`,
		planID, customerID, prefix)
	if err != nil {
		return false
	}
	defer rows.Close()
	want := strings.TrimSpace(product)
	wantKey := ""
	if want != "" {
		wantKey = model.VisitProductSlotKey(want)
	}
	any := false
	for rows.Next() {
		var pt string
		if err := rows.Scan(&pt); err != nil {
			return false
		}
		any = true
		if wantKey == "" {
			continue
		}
		if model.VisitProductSlotKey(pt) == wantKey {
			return true
		}
	}
	if wantKey != "" {
		return false
	}
	return any
}

// SetVisitDate 일일 업무 등록에서 점검 카드를 다른 날짜로 옮겼을 때 방문일을 맞춘다.
// 완료된 방문은 실적이므로 그대로 두고, 같은 날 같은 대상이 이미 있으면 조용히 넘긴다.
func (r *MaintenanceRepo) SetVisitDate(visitID, visitDate string) error {
	visitID = strings.TrimSpace(visitID)
	parsed, err := model.ParseAppDate(visitDate)
	if err != nil {
		return err
	}
	visitDate = parsed
	if visitID == "" || visitDate == "" {
		return nil
	}
	_, err = r.db.Exec(`
		UPDATE maintenance_visits SET visit_date=?
		WHERE visit_id=? AND visit_date!=? AND COALESCE(completed,0)=0`,
		visitDate, visitID, visitDate)
	if err != nil && strings.Contains(strings.ToUpper(err.Error()), "UNIQUE") {
		return nil
	}
	return err
}

// SetVisitCompleted 방문 완료 표시를 켜고 끈다. 끄면 실제 방문일도 지운다.
func (r *MaintenanceRepo) SetVisitCompleted(visitID string, done bool, doneDate string) error {
	var label string
	_ = r.db.QueryRow(`SELECT COALESCE(visit_date,'') FROM maintenance_visits WHERE visit_id=?`, visitID).Scan(&label)
	if label == "" {
		label = visitID
	}
	return touchUpdate(r.db, "maintenance_visits", "visit_id", visitID, label, func() error {
		if !done {
			_, err := r.db.Exec(
				`UPDATE maintenance_visits SET completed=0, completed_date=NULL WHERE visit_id=?`, visitID)
			return err
		}
		if doneDate == "" {
			_, err := r.db.Exec(
				`UPDATE maintenance_visits SET completed=1, completed_date=visit_date WHERE visit_id=?`, visitID)
			return err
		}
		_, err := r.db.Exec(
			`UPDATE maintenance_visits SET completed=1, completed_date=? WHERE visit_id=?`, doneDate, visitID)
		return err
	})
}

// CompleteVisitsUntil 지정일까지의 방문을 한 번에 완료 처리한다(과거 일정 일괄 정리용).
// onlyAssignees가 있으면 해당 담당자명만 처리한다(기술담당 내 일정 범위).
func (r *MaintenanceRepo) CompleteVisitsUntil(planID, until string, onlyAssignees []string) (int, error) {
	where := `plan_id=? AND visit_date <= ? AND COALESCE(completed,0)=0`
	args := []interface{}{planID, until}
	names := cleanAssignees(onlyAssignees)
	if len(names) > 0 {
		parts := make([]string, len(names))
		for i, n := range names {
			parts[i] = "LOWER(TRIM(COALESCE(assignee,''))) = LOWER(?)"
			args = append(args, n)
		}
		where += " AND (" + strings.Join(parts, " OR ") + ")"
	}
	rows, err := r.db.Query(`SELECT visit_id, COALESCE(visit_date,'') FROM maintenance_visits WHERE `+where, args...)
	if err != nil {
		return 0, err
	}
	type hit struct{ id, date, before string }
	var hits []hit
	for rows.Next() {
		var id, date string
		if err := rows.Scan(&id, &date); err != nil {
			rows.Close()
			return 0, err
		}
		hits = append(hits, hit{id: id, date: date})
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return 0, err
	}
	if len(hits) == 0 {
		return 0, nil
	}
	for i := range hits {
		hits[i].before = rowJSON(r.db, "maintenance_visits", "visit_id", hits[i].id)
	}
	res, err := r.db.Exec(`
		UPDATE maintenance_visits
		SET completed=1, completed_date=COALESCE(NULLIF(completed_date,''), visit_date)
		WHERE `+where, args...)
	if err != nil {
		return 0, err
	}
	for _, h := range hits {
		logUpdate(r.db, "maintenance_visits", "visit_id", h.id, h.date, h.before)
	}
	n, _ := res.RowsAffected()
	return int(n), nil
}

func nullIfEmpty(s string) interface{} {
	if s == "" {
		return nil
	}
	return s
}

func (r *MaintenanceRepo) DeleteVisit(visitID string) error {
	v, err := r.GetVisit(visitID)
	if err != nil {
		return err
	}
	if v == nil {
		return fmt.Errorf("방문을 찾을 수 없습니다")
	}
	if v.Completed {
		return fmt.Errorf("완료된 방문은 삭제할 수 없습니다")
	}
	if model.VisitDeleteProtected(v.VisitDate, r.nowTime()) {
		return ErrVisitDeleteProtected
	}
	return r.removeVisitRow(visitID)
}

func (r *MaintenanceRepo) removeVisitRow(visitID string) error {
	err := touchDelete(r.db, "maintenance_visits", "visit_id", visitID, "정기점검", func() error {
		_, err := r.db.Exec(`DELETE FROM maintenance_visits WHERE visit_id = ?`, visitID)
		return err
	})
	if err != nil {
		return err
	}
	_, _ = r.db.Exec(`DELETE FROM work_tasks WHERE source_type='maintenance' AND source_id=?`, visitID)
	return nil
}

func (r *MaintenanceRepo) ListSiteConfigs() ([]model.MaintenanceSiteConfig, error) {
	rows, err := r.db.Query(`
		SELECT s.customer_id, s.short_name, COALESCE(s.region,''),
		       s.has_klas, s.has_rfid, COALESCE(s.inspection_cycle,'monthly'),
		       s.entry_category, COALESCE(s.fixed_rule,''),
		       COALESCE(c.org_name,''),
		       COALESCE(c.addr_sido,''), COALESCE(c.addr_sigungu,'')
		FROM maintenance_site_config s
		LEFT JOIN customers c ON c.customer_id = s.customer_id
		ORDER BY s.region, s.short_name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []model.MaintenanceSiteConfig
	for rows.Next() {
		var cfg model.MaintenanceSiteConfig
		var klas, rfid int
		if err := rows.Scan(&cfg.CustomerID, &cfg.ShortName, &cfg.Region, &klas, &rfid, &cfg.InspectionCycle, &cfg.EntryCategory, &cfg.FixedRule, &cfg.OrgName, &cfg.AddrSido, &cfg.AddrSigungu); err != nil {
			return nil, err
		}
		cfg.HasKlas = klas == 1
		cfg.HasRfid = rfid == 1
		out = append(out, cfg)
	}
	return out, rows.Err()
}

func (r *MaintenanceRepo) GetSiteConfig(customerID string) (*model.MaintenanceSiteConfig, error) {
	var c model.MaintenanceSiteConfig
	var klas, rfid int
	err := r.db.QueryRow(`
		SELECT customer_id, short_name, COALESCE(region,''),
		       has_klas, has_rfid, COALESCE(inspection_cycle,'monthly'),
		       entry_category, COALESCE(fixed_rule,'')
		FROM maintenance_site_config WHERE customer_id = ?`, customerID).
		Scan(&c.CustomerID, &c.ShortName, &c.Region, &klas, &rfid, &c.InspectionCycle, &c.EntryCategory, &c.FixedRule)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	c.HasKlas = klas == 1
	c.HasRfid = rfid == 1
	return &c, nil
}

func (r *MaintenanceRepo) UpsertSiteConfig(c *model.MaintenanceSiteConfig) error {
	klas, rfid := 0, 0
	if c.HasKlas {
		klas = 1
	}
	if c.HasRfid {
		rfid = 1
	}
	if c.InspectionCycle == "" {
		c.InspectionCycle = "monthly"
	}
	res, err := r.db.Exec(`
		UPDATE maintenance_site_config SET
			short_name = ?, region = ?, has_klas = ?, has_rfid = ?,
			inspection_cycle = ?, entry_category = ?, fixed_rule = ?, updated_at = CURRENT_TIMESTAMP
		WHERE customer_id = ?`,
		c.ShortName, c.Region, klas, rfid, c.InspectionCycle, c.EntryCategory, nullString(c.FixedRule), c.CustomerID)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n > 0 {
		return nil
	}
	_, err = r.db.Exec(`
		INSERT INTO maintenance_site_config
		(customer_id, short_name, region, has_klas, has_rfid, inspection_cycle, entry_category, fixed_rule, updated_at)
		VALUES (?,?,?,?,?,?,?,?, CURRENT_TIMESTAMP)`,
		c.CustomerID, c.ShortName, c.Region, klas, rfid, c.InspectionCycle, c.EntryCategory, nullString(c.FixedRule))
	return err
}

func nullString(s string) interface{} {
	if s == "" {
		return nil
	}
	return s
}

func (r *MaintenanceRepo) DeleteSiteConfig(customerID string) error {
	_, err := r.db.Exec(`DELETE FROM maintenance_site_config WHERE customer_id = ?`, customerID)
	return err
}

// ListCustomersWithoutConfig 점검 설정이 없는 활성 고객 (선택용)
func (r *MaintenanceRepo) ListCustomersWithoutConfig() ([]struct{ ID, OrgName string }, error) {
	rows, err := r.db.Query(`
		SELECT c.customer_id, c.org_name FROM customers c
		WHERE c.is_active = 1
		  AND COALESCE(NULLIF(TRIM(c.party_kind),''),'customer')='customer'
		  AND NOT EXISTS (
			SELECT 1 FROM maintenance_site_config s WHERE s.customer_id = c.customer_id
		) ORDER BY c.org_name LIMIT 500`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []struct{ ID, OrgName string }
	for rows.Next() {
		var id, name string
		if err := rows.Scan(&id, &name); err != nil {
			return nil, err
		}
		out = append(out, struct{ ID, OrgName string }{id, name})
	}
	return out, rows.Err()
}

// periodicCycleRank 점검 간격이 짧은 순. 한 기관에 주기가 섞여 있으면 가장 짧은 주기를 따른다.
var periodicCycleRank = map[string]int{
	"monthly":        1,
	"odd_bimonthly":  2,
	"even_bimonthly": 2,
	"quarterly":      3,
	"semi":           4,
	"yearly":         5,
}

// SiteConfigSyncResult 자산 기준 일괄 생성 결과
type SiteConfigSyncResult struct {
	Added   int      // 새로 만든 사이트 설정 수
	Skipped int      // 이미 설정이 있어 건너뛴 기관 수
	Names   []string // 새로 만든 기관명
}

// SyncSiteConfigsFromAssets 유상 유지보수 계약 + 정기 점검주기를 가진 자산의 기관에
// 점검 사이트 설정을 만든다. 이미 설정이 있는 기관은 손대지 않는다.
func (r *MaintenanceRepo) SyncSiteConfigsFromAssets() (SiteConfigSyncResult, error) {
	var res SiteConfigSyncResult
	targets, skipped, err := r.siteConfigCandidates()
	if err != nil {
		return res, err
	}
	res.Skipped = skipped

	for _, cfg := range targets {
		c := cfg
		if err := r.UpsertSiteConfig(&c); err != nil {
			return res, fmt.Errorf("%s 설정 생성: %w", c.ShortName, err)
		}
		res.Added++
		res.Names = append(res.Names, c.ShortName)
	}
	return res, nil
}

// PreviewSiteConfigsFromAssets 저장하지 않고 추가 대상만 계산
func (r *MaintenanceRepo) PreviewSiteConfigsFromAssets() ([]model.MaintenanceSiteConfig, error) {
	targets, _, err := r.siteConfigCandidates()
	return targets, err
}

func (r *MaintenanceRepo) siteConfigCandidates() ([]model.MaintenanceSiteConfig, int, error) {
	skipped := 0
	rows, err := r.db.Query(`
		SELECT a.customer_id,
		       COALESCE(NULLIF(TRIM(c.org_name),''), NULLIF(TRIM(c.official_name),''), a.customer_id),
		       COALESCE(c.addr_sido,''),
		       GROUP_CONCAT(DISTINCT TRIM(LOWER(a.maint_cycle))),
		       MAX(CASE WHEN LOWER(COALESCE(a.product_category,'')) = 'rfid' THEN 1 ELSE 0 END),
		       MAX(CASE WHEN UPPER(COALESCE(a.product_name,'')) LIKE '%KLAS%'
		                  OR UPPER(COALESCE(a.model_name,'')) LIKE '%KLAS%' THEN 1 ELSE 0 END),
		       MAX(CASE WHEN EXISTS (SELECT 1 FROM maintenance_site_config s
		                             WHERE s.customer_id = a.customer_id) THEN 1 ELSE 0 END)
		FROM assets a
		JOIN customers c ON c.customer_id = a.customer_id
		WHERE TRIM(LOWER(COALESCE(a.maint_contract_type,''))) = 'paid'
		  AND COALESCE(a.is_managed,1)=1
		  AND LOWER(TRIM(COALESCE(a.management_type,''))) != 'third_party'
		  AND TRIM(LOWER(COALESCE(a.maint_cycle,''))) IN
		      ('monthly','odd_bimonthly','even_bimonthly','quarterly','semi','yearly')
		GROUP BY a.customer_id
		ORDER BY 2`)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var targets []model.MaintenanceSiteConfig
	for rows.Next() {
		var customerID, orgName, sido, cycles string
		var hasRfid, hasKlas, exists int
		if err := rows.Scan(&customerID, &orgName, &sido, &cycles, &hasRfid, &hasKlas, &exists); err != nil {
			return nil, 0, err
		}
		if exists == 1 {
			skipped++
			continue
		}
		targets = append(targets, model.MaintenanceSiteConfig{
			CustomerID:      customerID,
			ShortName:       strings.TrimSpace(orgName),
			Region:          shortRegionName(sido),
			HasKlas:         hasKlas == 1,
			HasRfid:         hasRfid == 1,
			InspectionCycle: shortestCycle(cycles),
			EntryCategory:   "normal",
			OrgName:         strings.TrimSpace(orgName),
		})
	}
	if err := rows.Err(); err != nil {
		return nil, 0, err
	}
	return targets, skipped, nil
}

// shortestCycle GROUP_CONCAT 으로 모인 주기 중 간격이 가장 짧은 값
func shortestCycle(concat string) string {
	best, bestRank := "monthly", 99
	for _, v := range strings.Split(concat, ",") {
		v = strings.TrimSpace(v)
		rank, ok := periodicCycleRank[v]
		if ok && rank < bestRank {
			best, bestRank = v, rank
		}
	}
	return best
}

// shortRegionName 행정구역 정식명칭을 점검표에 쓰는 축약형으로 (충청남도 → 충남)
func shortRegionName(sido string) string {
	s := strings.TrimSpace(sido)
	if s == "" {
		return ""
	}
	short := map[string]string{
		"서울특별시": "서울", "부산광역시": "부산", "대구광역시": "대구", "인천광역시": "인천",
		"광주광역시": "광주", "대전광역시": "대전", "울산광역시": "울산",
		"세종특별자치시": "세종", "경기도": "경기", "강원도": "강원", "강원특별자치도": "강원",
		"충청북도": "충북", "충청남도": "충남", "전라북도": "전북", "전북특별자치도": "전북",
		"전라남도": "전남", "경상북도": "경북", "경상남도": "경남",
		"제주도": "제주", "제주특별자치도": "제주",
	}
	if v, ok := short[s]; ok {
		return v
	}
	return s
}

// TouchPlanUpdated 계획 수정 시각
func (r *MaintenanceRepo) TouchPlanUpdated(planID string) {
	_, _ = r.db.Exec(`UPDATE maintenance_plans SET updated_at = CURRENT_TIMESTAMP WHERE plan_id = ?`, planID)
}
