package repository

import (
	"errors"
	"path/filepath"
	"testing"
	"time"

	"customer-support/internal/model"
)

func protectRepo(t *testing.T, name string) (*MaintenanceRepo, func()) {
	t.Helper()
	db, err := InitDB(filepath.Join(t.TempDir(), name))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
		VALUES ('c1','가나도서관','가나도서관',1)`); err != nil {
		t.Fatal(err)
	}
	repo := NewMaintenanceRepo(db)
	repo.Now = func() time.Time { return time.Date(2026, 8, 17, 12, 0, 0, 0, time.Local) }
	return repo, func() { db.Close() }
}

func TestDeleteVisitRejectsCurrentAndPastMonth(t *testing.T) {
	repo, close := protectRepo(t, "del_protect.db")
	defer close()
	p, err := repo.CreatePlan(2026, "2026년 정기점검")
	if err != nil {
		t.Fatal(err)
	}
	for _, date := range []string{"2026-07-10", "2026-08-10"} {
		if err := repo.InsertVisit(p.PlanID, date, "c1", 0, 0, "normal", ""); err != nil {
			t.Fatal(err)
		}
	}
	visits, _ := repo.ListVisits(p.PlanID)
	if len(visits) != 2 {
		t.Fatalf("setup: %d", len(visits))
	}
	for _, v := range visits {
		if err := repo.DeleteVisit(v.VisitID); !errors.Is(err, ErrVisitDeleteProtected) {
			t.Fatalf("%s 삭제 오류: %v", v.VisitDate, err)
		}
	}
	left, _ := repo.ListVisits(p.PlanID)
	if len(left) != 2 {
		t.Fatalf("보호 방문이 지워짐: %d", len(left))
	}
}

func TestDeleteVisitAllowsNextMonth(t *testing.T) {
	repo, close := protectRepo(t, "del_future.db")
	defer close()
	p, err := repo.CreatePlan(2026, "t")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisit(p.PlanID, "2026-09-10", "c1", 0, 0, "normal", ""); err != nil {
		t.Fatal(err)
	}
	visits, _ := repo.ListVisits(p.PlanID)
	if err := repo.DeleteVisit(visits[0].VisitID); err != nil {
		t.Fatal(err)
	}
	left, _ := repo.ListVisits(p.PlanID)
	if len(left) != 0 {
		t.Fatalf("미래 방문이 남음: %d", len(left))
	}
}

func TestDeleteVisitIDsSkipsProtected(t *testing.T) {
	repo, close := protectRepo(t, "bulk.db")
	defer close()
	p, err := repo.CreatePlan(2026, "t")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisit(p.PlanID, "2026-08-10", "c1", 0, 0, "normal", "당월"); err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisit(p.PlanID, "2026-09-10", "c1", 0, 0, "normal", "다음달"); err != nil {
		t.Fatal(err)
	}
	visits, _ := repo.ListVisits(p.PlanID)
	ids := []string{visits[0].VisitID, visits[1].VisitID}
	deleted, skipped, err := repo.DeleteVisitIDs(ids)
	if err != nil {
		t.Fatal(err)
	}
	if deleted != 1 || skipped != 1 {
		t.Fatalf("deleted=%d skipped=%d", deleted, skipped)
	}
	left, _ := repo.ListVisits(p.PlanID)
	if len(left) != 1 || left[0].VisitDate != "2026-08-10" {
		t.Fatalf("남은 방문: %+v", left)
	}
}

func TestDeletePlanRejectsProtectedAndCompleted(t *testing.T) {
	repo, close := protectRepo(t, "plan_guard.db")
	defer close()
	p, err := repo.CreatePlan(2026, "2026년 정기점검")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisit(p.PlanID, "2026-08-10", "c1", 0, 0, "normal", ""); err != nil {
		t.Fatal(err)
	}
	err = repo.DeletePlan(p.PlanID)
	if err == nil || err.Error() == "" {
		t.Fatal("당월 방문이 있는데 계획이 지워짐")
	}
	if got := err.Error(); got != model.ProtectedVisitRangeMessage(repo.Now(), 1) {
		t.Fatalf("거부 문구: %s", got)
	}
	if _, err := repo.GetPlan(p.PlanID); err != nil {
		t.Fatal(err)
	}

	fut, err := repo.CreatePlan(2027, "2027년 정기점검")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisit(fut.PlanID, "2027-03-10", "c1", 0, 0, "normal", ""); err != nil {
		t.Fatal(err)
	}
	visits, _ := repo.ListVisits(fut.PlanID)
	if err := repo.SetVisitCompleted(visits[0].VisitID, true, "2027-03-10"); err != nil {
		t.Fatal(err)
	}
	if err := repo.DeletePlan(fut.PlanID); err == nil {
		t.Fatal("완료 방문이 있는데 계획이 지워짐")
	}
}

func TestDeletePlanPastYearRejected(t *testing.T) {
	repo, close := protectRepo(t, "past_year.db")
	defer close()
	p, err := repo.CreatePlan(2025, "2025년 정기점검")
	if err != nil {
		t.Fatal(err)
	}
	err = repo.DeletePlan(p.PlanID)
	if err == nil {
		t.Fatal("지난 연도 계획이 지워짐")
	}
}

func TestDeleteAutoVisitsSkipsProtected(t *testing.T) {
	repo, close := protectRepo(t, "auto.db")
	defer close()
	p, err := repo.CreatePlan(2026, "t")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-08-10", CustomerID: "c1", AutoGenerated: true, ProductType: "KLAS",
	}); err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-09-10", CustomerID: "c1", AutoGenerated: true, ProductType: "KLAS",
	}); err != nil {
		t.Fatal(err)
	}
	deleted, skipped, err := repo.DeleteAutoVisits(p.PlanID)
	if err != nil {
		t.Fatal(err)
	}
	if deleted != 1 || skipped != 1 {
		t.Fatalf("deleted=%d skipped=%d", deleted, skipped)
	}
	left, _ := repo.ListVisits(p.PlanID)
	if len(left) != 1 || left[0].VisitDate != "2026-08-10" {
		t.Fatalf("남은 자동 방문: %+v", left)
	}
}

func TestCollapseDuplicateSkipsProtected(t *testing.T) {
	repo, close := protectRepo(t, "collapse_protect.db")
	defer close()
	p, err := repo.CreatePlan(2026, "t")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-08-10", CustomerID: "c1", ProductType: "KLAS", AutoGenerated: true,
	}); err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-08-14", CustomerID: "c1", ProductType: "KLAS",
	}); err != nil {
		t.Fatal(err)
	}
	deleted, skipped, err := repo.CollapseDuplicateMonthVisits(p.PlanID, 2026, 8)
	if err != nil {
		t.Fatal(err)
	}
	if deleted != 0 || skipped != 1 {
		t.Fatalf("deleted=%d skipped=%d (당월 중복은 지우면 안 됨)", deleted, skipped)
	}
	left, _ := repo.ListVisitsByMonth(p.PlanID, 2026, 8)
	if len(left) != 2 {
		t.Fatalf("당월 중복이 지워짐: %d", len(left))
	}
}
