package service

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"customer-support/internal/model"
	"customer-support/internal/repository"
)

func TestAutoGenerateMaintenance(t *testing.T) {
	dir := t.TempDir()
	db, err := repository.InitDB(filepath.Join(dir, "gen.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	for _, id := range []string{"c1", "c2", "c3"} {
		_, err = db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active) VALUES (?,?,?,1)`,
			id, "Org "+id, "Org "+id)
		if err != nil {
			t.Fatal(err)
		}
	}

	repo := repository.NewMaintenanceRepo(db)
	for i, id := range []string{"c1", "c2", "c3"} {
		cat := "normal"
		if i == 2 {
			cat = "fixed"
		}
		fr := ""
		if i == 2 {
			fr = fixedRuleLastMonday
		}
		if err := repo.UpsertSiteConfig(&model.MaintenanceSiteConfig{
			CustomerID: id, ShortName: id, Region: "R1",
			HasKlas: true, EntryCategory: cat, FixedRule: fr,
		}); err != nil {
			t.Fatal(err)
		}
	}

	p, err := repo.CreatePlan(2026, "자동배정 테스트")
	if err != nil {
		t.Fatal(err)
	}

	if err := AutoGenerateMaintenance(repo, p.PlanID); err != nil {
		t.Fatal(err)
	}

	visits, err := repo.ListVisits(p.PlanID)
	if err != nil {
		t.Fatal(err)
	}
	// 월별: 고정 1 + flex 2 → 보통 36건. 마지막 월요일이 공휴일과 겹치는 달은 고정 건을 건너뛸 수 있어 35건 등이 될 수 있다.
	if len(visits) < 34 || len(visits) > 36 {
		t.Fatalf("expected about 36 visits, got %d", len(visits))
	}
	for _, v := range visits {
		if model.VisitProductSlotKey(v.ProductType) != "klas" {
			t.Fatalf("product_type=%q want KLAS", v.ProductType)
		}
	}

	repo.Now = func() time.Time { return time.Date(2025, 12, 1, 0, 0, 0, 0, time.Local) }
	deleted, skipped, err := repo.DeleteAutoVisits(p.PlanID)
	if err != nil {
		t.Fatal(err)
	}
	if skipped != 0 {
		t.Fatalf("보호로 건너뛴 건: %d (시계를 2025-12로 두면 2026년 방문은 지울 수 있어야 함)", skipped)
	}
	visits, _ = repo.ListVisits(p.PlanID)
	if len(visits) != 0 {
		t.Fatalf("after DeleteAutoVisits: len=%d deleted=%d", len(visits), deleted)
	}
}

func TestAutoGenerateDualProductClearsUnassigned(t *testing.T) {
	dir := t.TempDir()
	db, err := repository.InitDB(filepath.Join(dir, "dual.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
		VALUES ('c_dual','둘다도서관','둘다도서관',1)`); err != nil {
		t.Fatal(err)
	}
	repo := repository.NewMaintenanceRepo(db)
	if err := repo.UpsertSiteConfig(&model.MaintenanceSiteConfig{
		CustomerID: "c_dual", ShortName: "둘다", Region: "서울",
		HasKlas: true, HasRfid: true, InspectionCycle: "monthly",
	}); err != nil {
		t.Fatal(err)
	}
	p, err := repo.CreatePlan(2026, "이중 대상")
	if err != nil {
		t.Fatal(err)
	}
	if err := AutoGenerateMaintenance(repo, p.PlanID); err != nil {
		t.Fatal(err)
	}

	for m := 1; m <= 12; m++ {
		visits, err := repo.ListVisitsByMonth(p.PlanID, 2026, m)
		if err != nil {
			t.Fatal(err)
		}
		if len(visits) != 2 {
			t.Fatalf("%d월 방문=%d want 2 (KLAS+RFID)", m, len(visits))
		}
		seen := map[string]bool{}
		for _, v := range visits {
			if strings.TrimSpace(v.ProductType) == "" {
				t.Fatalf("%d월 product_type 비어 있음", m)
			}
			k := model.VisitProductSlotKey(v.ProductType)
			if k != "klas" && k != "rfid" {
				t.Fatalf("%d월 슬롯=%q", m, v.ProductType)
			}
			if seen[k] {
				t.Fatalf("%d월 %s 중복", m, k)
			}
			seen[k] = true
			day, _ := strconv.Atoi(v.VisitDate[8:10])
			if day > 24 {
				t.Fatalf("%d월 flex 방문이 25일 이후: %s", m, v.VisitDate)
			}
		}
		if !seen["klas"] || !seen["rfid"] {
			t.Fatalf("%d월 슬롯=%v want klas+rfid", m, seen)
		}
		unassigned, err := repo.ListUnassignedMonthSlots(p.PlanID, 2026, m)
		if err != nil {
			t.Fatal(err)
		}
		if len(unassigned) != 0 {
			t.Fatalf("%d월 미배정=%d want 0: %+v", m, len(unassigned), unassigned)
		}
	}
}

func TestAutoGenerateHonorsInspectionCycle(t *testing.T) {
	dir := t.TempDir()
	db, err := repository.InitDB(filepath.Join(dir, "cycle.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
		VALUES ('c_odd','홀수도서관','홀수도서관',1)`); err != nil {
		t.Fatal(err)
	}
	repo := repository.NewMaintenanceRepo(db)
	if err := repo.UpsertSiteConfig(&model.MaintenanceSiteConfig{
		CustomerID: "c_odd", ShortName: "홀수", HasKlas: true,
		InspectionCycle: "odd_bimonthly",
	}); err != nil {
		t.Fatal(err)
	}
	p, err := repo.CreatePlan(2026, "주기")
	if err != nil {
		t.Fatal(err)
	}
	if err := AutoGenerateMaintenance(repo, p.PlanID); err != nil {
		t.Fatal(err)
	}
	for m := 1; m <= 12; m++ {
		visits, err := repo.ListVisitsByMonth(p.PlanID, 2026, m)
		if err != nil {
			t.Fatal(err)
		}
		due := model.InspectionCycleDue("odd_bimonthly", m)
		if due && len(visits) != 1 {
			t.Fatalf("%d월 도래인데 방문=%d", m, len(visits))
		}
		if !due && len(visits) != 0 {
			t.Fatalf("%d월 비도래인데 방문=%d", m, len(visits))
		}
	}
}

func TestAutoGenerateOverflowStaysUnassigned(t *testing.T) {
	dir := t.TempDir()
	db, err := repository.InitDB(filepath.Join(dir, "cap.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO app_settings(setting_key, setting_value, updated_at)
		VALUES (?, '1', '2026-01-01T00:00:00Z')`, repository.SettingMaintenanceAutoDailyLimit); err != nil {
		t.Fatal(err)
	}
	repo := repository.NewMaintenanceRepo(db)
	const nSites = 20
	for i := 0; i < nSites; i++ {
		id := fmt.Sprintf("c%02d", i)
		if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
			VALUES (?,?,?,1)`, id, id, id); err != nil {
			t.Fatal(err)
		}
		if err := repo.UpsertSiteConfig(&model.MaintenanceSiteConfig{
			CustomerID: id, ShortName: id, Region: "R",
			HasKlas: true, InspectionCycle: "yearly",
		}); err != nil {
			t.Fatal(err)
		}
	}
	p, err := repo.CreatePlan(2026, "상한")
	if err != nil {
		t.Fatal(err)
	}
	if err := AutoGenerateMaintenance(repo, p.PlanID); err != nil {
		t.Fatal(err)
	}

	jan, err := repo.ListVisitsByMonth(p.PlanID, 2026, 1)
	if err != nil {
		t.Fatal(err)
	}
	workdays := workdaysBefore25(2026, 1, time.Local, NewCalendar(repo.Holidays()))
	if len(jan) != len(workdays) {
		t.Fatalf("1월 방문=%d want %d (하루 1건 × 25일 이전 평일)", len(jan), len(workdays))
	}
	for _, v := range jan {
		day, _ := strconv.Atoi(v.VisitDate[8:10])
		if day > 24 {
			t.Fatalf("26일 이후로 밀어 넣음: %s", v.VisitDate)
		}
	}
	unassigned, err := repo.ListUnassignedMonthSlots(p.PlanID, 2026, 1)
	if err != nil {
		t.Fatal(err)
	}
	wantLeft := nSites - len(workdays)
	if len(unassigned) != wantLeft {
		t.Fatalf("미배정=%d want %d", len(unassigned), wantLeft)
	}
	aug, _ := repo.ListVisitsByMonth(p.PlanID, 2026, 8)
	if len(aug) != 0 {
		t.Fatalf("년1회인데 8월 방문=%d", len(aug))
	}
}

func TestHasVisitInMonthIsPerProduct(t *testing.T) {
	dir := t.TempDir()
	db, err := repository.InitDB(filepath.Join(dir, "has.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
		VALUES ('c1','가나','가나',1)`); err != nil {
		t.Fatal(err)
	}
	repo := repository.NewMaintenanceRepo(db)
	p, err := repo.CreatePlan(2026, "t")
	if err != nil {
		t.Fatal(err)
	}
	if err := repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID: p.PlanID, VisitDate: "2026-08-10", CustomerID: "c1", ProductType: "KLAS",
	}); err != nil {
		t.Fatal(err)
	}
	if !repo.HasVisitInMonth(p.PlanID, "c1", 2026, 8, "KLAS") {
		t.Fatal("KLAS 방문이 있어야 함")
	}
	if repo.HasVisitInMonth(p.PlanID, "c1", 2026, 8, "앤로보틱스") {
		t.Fatal("RFID 없는데 true")
	}
	if !repo.HasVisitInMonth(p.PlanID, "c1", 2026, 8, "") {
		t.Fatal("기관 전체는 있어야 함")
	}
}

func TestAutoGenerate2026SeptemberSkipsChuseok(t *testing.T) {
	dir := t.TempDir()
	db, err := repository.InitDB(filepath.Join(dir, "chuseok.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec(`INSERT INTO app_settings(setting_key, setting_value, updated_at)
		VALUES (?, '1', '2026-01-01T00:00:00Z')`, repository.SettingMaintenanceAutoDailyLimit); err != nil {
		t.Fatal(err)
	}
	repo := repository.NewMaintenanceRepo(db)
	const nSites = 20
	for i := 0; i < nSites; i++ {
		id := fmt.Sprintf("s%02d", i)
		if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active)
			VALUES (?,?,?,1)`, id, id, id); err != nil {
			t.Fatal(err)
		}
		if err := repo.UpsertSiteConfig(&model.MaintenanceSiteConfig{
			CustomerID: id, ShortName: id, Region: "R",
			HasKlas: true, InspectionCycle: "monthly",
		}); err != nil {
			t.Fatal(err)
		}
	}
	p, err := repo.CreatePlan(2026, "추석 검증")
	if err != nil {
		t.Fatal(err)
	}
	if err := AutoGenerateMaintenance(repo, p.PlanID); err != nil {
		t.Fatal(err)
	}
	sep, err := repo.ListVisitsByMonth(p.PlanID, 2026, 9)
	if err != nil {
		t.Fatal(err)
	}
	days := workdaysBefore25(2026, 9, time.Local, NewCalendar(repo.Holidays()))
	if len(sep) != len(days) {
		t.Fatalf("9월 방문=%d want %d (하루 1건 × 추석 제외 평일)", len(sep), len(days))
	}
	for _, v := range sep {
		switch v.VisitDate {
		case "2026-09-24", "2026-09-25", "2026-09-26":
			t.Fatalf("추석에 방문이 잡힘: %s", v.VisitDate)
		}
	}
	for _, d := range days {
		if d == "2026-09-24" {
			t.Fatal("9/24가 배정 평일에 남아 있다")
		}
	}
}

func TestWorkdaysForMonth(t *testing.T) {
	days := workdaysForMonth(2026, 3, time.Local)
	if len(days) < 10 {
		t.Fatalf("expected enough workdays, got %d", len(days))
	}
	for _, ds := range days {
		day, _ := strconv.Atoi(ds[8:10])
		if day > 24 {
			t.Fatalf("25일 이후 평일 포함: %s", ds)
		}
	}
}

func TestAutoGenerateSkipsAssigneeOnLeave(t *testing.T) {
	dir := t.TempDir()
	db, err := repository.InitDB(filepath.Join(dir, "genleave.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	SetHolidayCalendar(NewCalendar(repository.NewHolidayRepo(db)))
	t.Cleanup(func() { SetHolidayCalendar(nil) })

	if _, err := db.Exec(`INSERT INTO customers (customer_id, org_name, official_name, is_active) VALUES ('c1','도서관','도서관',1)`); err != nil {
		t.Fatal(err)
	}
	u := &model.User{Username: "yang", PasswordHash: "x", FullName: "양기헌", Role: model.RoleTech, IsActive: true}
	if err := repository.NewUserRepo(db).Create(u); err != nil {
		t.Fatal(err)
	}
	mnt := repository.NewMaintenanceRepo(db)
	if err := mnt.UpsertSiteConfig(&model.MaintenanceSiteConfig{
		CustomerID: "c1", ShortName: "도서관", Region: "R1", HasKlas: true, InspectionCycle: "monthly",
	}); err != nil {
		t.Fatal(err)
	}
	prev, err := mnt.CreatePlan(2025, "2025")
	if err != nil {
		t.Fatal(err)
	}
	if err := mnt.InsertVisitFull(model.MaintenanceVisit{
		PlanID: prev.PlanID, VisitDate: "2025-12-10", CustomerID: "c1", ProductType: "KLAS", Assignee: "양기헌",
	}); err != nil {
		t.Fatal(err)
	}
	plan, err := mnt.CreatePlan(2026, "2026")
	if err != nil {
		t.Fatal(err)
	}
	if err := repository.NewStaffLeaveRepo(db).Create(model.StaffLeave{
		UserID: u.UserID, UserName: u.FullName, Date: "2026-01-02", Kind: model.LeaveKindAnnual,
	}); err != nil {
		t.Fatal(err)
	}
	if err := AutoGenerateMaintenance(mnt, plan.PlanID); err != nil {
		t.Fatal(err)
	}
	visits, err := mnt.ListVisits(plan.PlanID)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, v := range visits {
		if v.VisitDate == "2026-01-02" {
			found = true
			if strings.TrimSpace(v.Assignee) != "" {
				t.Fatalf("연차인 사람에게 자동배정됨 assignee=%q", v.Assignee)
			}
		}
	}
	if !found {
		t.Fatal("2026-01-02 방문이 없음")
	}
}
