package service

import (
	"errors"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"customer-support/internal/model"
	"customer-support/internal/repository"
)

var errMonthSkip = errors.New("month_skip")

const (
	GenerateOrderPrevMonth = "prev_month"
	GenerateOrderNear      = "near"
	GenerateOrderFar       = "far"
)

type generateSlot struct {
	cfg   model.MaintenanceSiteConfig
	slot  model.UnassignedMonthSlot
	fixed bool
}

type prevVisitRef struct {
	day       int
	sortOrder int
	region    string
	date      string
}

// NormalizeGenerateOrder 자동 배정 순서. 기본은 전월. §34.4.2
func NormalizeGenerateOrder(s string) string {
	switch strings.TrimSpace(s) {
	case GenerateOrderNear, "근거리":
		return GenerateOrderNear
	case GenerateOrderFar, "원거리":
		return GenerateOrderFar
	default:
		return GenerateOrderPrevMonth
	}
}

// AutoGenerateMaintenance 기획서 §23.5 · §34.4 자동 초안. 기본 순서는 전월.
func AutoGenerateMaintenance(repo *repository.MaintenanceRepo, planID string) error {
	_, err := AutoGenerateMaintenanceWithOrder(repo, planID, GenerateOrderPrevMonth, 0, 0)
	return err
}

// AutoGenerateMaintenanceWithOrder 주기 도래 사이트만, 점검대상별로 방문을 나누고
// 고정 규칙을 먼저 넣은 뒤 나머지를 선택한 순서로 25일 이전 평일에 나열한다.
// year·month 가 있으면 그 달만. month=0 이면 12개월(기존 연 단위). §34.4.5
func AutoGenerateMaintenanceWithOrder(repo *repository.MaintenanceRepo, planID, order string, year, month int) (int, error) {
	plan, err := repo.GetPlan(planID)
	if err != nil || plan == nil {
		return 0, fmt.Errorf("계획을 찾을 수 없습니다")
	}
	configs, err := repo.ListSiteConfigs()
	if err != nil {
		return 0, err
	}
	if len(configs) == 0 {
		return 0, fmt.Errorf("정기점검 사이트 설정이 없습니다. 먼저 「점검 사이트 설정」에서 등록하세요")
	}
	order = NormalizeGenerateOrder(order)
	dist, _ := repo.ListRegionDistanceOrder()
	distMap := regionOrderMap(dist)

	y := year
	if y < 2000 {
		y = plan.PlanYear
	}
	now := time.Now()
	if repo != nil && repo.Now != nil {
		now = repo.Now()
	}

	skipped := 0
	if month >= 1 && month <= 12 {
		if model.IsPastGenerateMonth(y, month, now) {
			return 0, model.ErrGeneratePastMonth
		}
		if _, _, err := repo.DeleteAutoVisitsInMonth(planID, y, month); err != nil {
			return 0, err
		}
	} else {
		if _, _, err := repo.DeleteAutoVisits(planID); err != nil {
			return 0, err
		}
	}

	loc := time.Local
	perDay := repo.AutoGenerateDailyLimit()
	cal := NewCalendar(repo.Holidays())
	cfgByID := map[string]model.MaintenanceSiteConfig{}
	for _, c := range configs {
		cfgByID[c.CustomerID] = c
	}

	from, to := 1, 12
	if month >= 1 && month <= 12 {
		from, to = month, month
	}
	for m := from; m <= to; m++ {
		fixed, flex := dueSlotsForMonth(configs, m)
		var prevForSort map[string]prevVisitRef
		if order == GenerateOrderPrevMonth {
			prevForSort = prevMonthRefs(repo, plan, m, cfgByID)
		}
		sortFlexSlots(flex, order, distMap, prevForSort)
		existing, err := repo.ListVisitsByMonth(planID, y, m)
		if err != nil {
			return 0, err
		}
		dayCount := map[string]int{}
		for _, v := range existing {
			dayCount[v.VisitDate]++
		}

		today := now.Format("2006-01-02")
		monthScoped := month >= 1 && month <= 12

		for _, it := range fixed {
			if repo.HasVisitInMonth(planID, it.cfg.CustomerID, y, m, it.slot.ProductType) {
				skipped++
				continue
			}
			dates := fixedDatesForMonth(y, m, it.cfg.FixedRule, loc, cal)
			if len(dates) == 0 {
				continue
			}
			ds := dates[0]
			if monthScoped && !dateAfterToday(ds, today) {
				continue
			}
			n, err := insertGeneratedOrSkip(repo, planID, ds, dayCount[ds], it)
			skipped += n
			if err != nil {
				return 0, err
			}
			if n == 0 {
				dayCount[ds]++
			}
		}

		workdays := workdaysBefore25(y, m, loc, cal)
		if monthScoped {
			workdays = filterDatesAfterToday(workdays, today)
		}
		var prevRefs map[string]prevVisitRef
		if order == GenerateOrderPrevMonth {
			prevRefs = prevMonthRefs(repo, plan, m, cfgByID)
		}
		for _, it := range flex {
			if repo.HasVisitInMonth(planID, it.cfg.CustomerID, y, m, it.slot.ProductType) {
				skipped++
				continue
			}
			ds, sortOrd, fromPrev := mappedPrevDate(it, prevRefs, y, m, loc, cal)
			if fromPrev && (!monthScoped || dateAfterToday(ds, today)) {
				n, err := insertGeneratedOrSkip(repo, planID, ds, sortOrd, it)
				skipped += n
				if err != nil {
					return 0, err
				}
				if n == 0 {
					dayCount[ds]++
				}
				continue
			}
			ds, ok := nextOpenWorkday(workdays, dayCount, perDay)
			if !ok {
				continue
			}
			n, err := insertGeneratedOrSkip(repo, planID, ds, dayCount[ds], it)
			skipped += n
			if err != nil {
				return 0, err
			}
			if n == 0 {
				dayCount[ds]++
			}
		}
	}

	repo.TouchPlanUpdated(planID)
	return skipped, nil
}

func dueSlotsForMonth(configs []model.MaintenanceSiteConfig, month int) (fixed, flex []generateSlot) {
	for _, c := range configs {
		slots := model.SiteDueProductSlots(c, month)
		isFixed := model.HasFixedRule(c.FixedRule)
		for _, s := range slots {
			it := generateSlot{cfg: c, slot: s, fixed: isFixed}
			if isFixed {
				fixed = append(fixed, it)
			} else {
				flex = append(flex, it)
			}
		}
	}
	sortGenerateSlots(fixed)
	sortGenerateSlots(flex)
	return fixed, flex
}

func sortGenerateSlots(items []generateSlot) {
	sort.SliceStable(items, func(i, j int) bool {
		if items[i].cfg.Region != items[j].cfg.Region {
			return items[i].cfg.Region < items[j].cfg.Region
		}
		if items[i].cfg.ShortName != items[j].cfg.ShortName {
			return items[i].cfg.ShortName < items[j].cfg.ShortName
		}
		if items[i].cfg.CustomerID != items[j].cfg.CustomerID {
			return items[i].cfg.CustomerID < items[j].cfg.CustomerID
		}
		return items[i].slot.SlotKey < items[j].slot.SlotKey
	})
}

func sortFlexSlots(items []generateSlot, order string, dist map[string]int, prev map[string]prevVisitRef) {
	if len(items) == 0 {
		return
	}
	switch order {
	case GenerateOrderNear, GenerateOrderFar:
		far := order == GenerateOrderFar
		sort.SliceStable(items, func(i, j int) bool {
			ri := lookupDistanceRank(items[i].cfg, dist, far)
			rj := lookupDistanceRank(items[j].cfg, dist, far)
			if ri != rj {
				return ri < rj
			}
			return generateSlotLess(items[i], items[j])
		})
	case GenerateOrderPrevMonth:
		if len(prev) == 0 {
			if len(dist) > 0 {
				sortFlexSlots(items, GenerateOrderNear, dist, nil)
				return
			}
			sortGenerateSlots(items)
			return
		}
		dom := dominantRegionByPrevDay(prev)
		sort.SliceStable(items, func(i, j int) bool {
			pi, iok := prev[slotPrevKey(items[i])]
			pj, jok := prev[slotPrevKey(items[j])]
			if iok != jok {
				return iok
			}
			if !iok {
				return generateSlotLess(items[i], items[j])
			}
			if pi.day != pj.day {
				return pi.day < pj.day
			}
			di := 1
			dj := 1
			if pi.region != "" && pi.region == dom[pi.date] {
				di = 0
			}
			if pj.region != "" && pj.region == dom[pj.date] {
				dj = 0
			}
			if di != dj {
				return di < dj
			}
			if pi.sortOrder != pj.sortOrder {
				return pi.sortOrder < pj.sortOrder
			}
			return generateSlotLess(items[i], items[j])
		})
	default:
		sortGenerateSlots(items)
	}
}

func generateSlotLess(a, b generateSlot) bool {
	if a.cfg.Region != b.cfg.Region {
		return a.cfg.Region < b.cfg.Region
	}
	if a.cfg.ShortName != b.cfg.ShortName {
		return a.cfg.ShortName < b.cfg.ShortName
	}
	if a.cfg.CustomerID != b.cfg.CustomerID {
		return a.cfg.CustomerID < b.cfg.CustomerID
	}
	return a.slot.SlotKey < b.slot.SlotKey
}

func slotPrevKey(it generateSlot) string {
	return it.cfg.CustomerID + "\x1f" + it.slot.ProductType
}

func prevMonthRefs(repo *repository.MaintenanceRepo, plan *model.MaintenancePlan, month int, cfgByID map[string]model.MaintenanceSiteConfig) map[string]prevVisitRef {
	if repo == nil || plan == nil {
		return nil
	}
	y, m, planID := plan.PlanYear, month-1, plan.PlanID
	if m < 1 {
		m = 12
		y--
		prev, err := repo.GetPlanByYear(y)
		if err != nil || prev == nil {
			return nil
		}
		planID = prev.PlanID
	}
	visits, err := repo.ListVisitsByMonth(planID, y, m)
	if err != nil || len(visits) == 0 {
		return nil
	}
	out := map[string]prevVisitRef{}
	for _, v := range visits {
		day := 0
		if len(v.VisitDate) >= 10 {
			day, _ = strconv.Atoi(v.VisitDate[8:10])
		}
		if day < 1 {
			continue
		}
		reg := ""
		if c, ok := cfgByID[v.CustomerID]; ok {
			reg = strings.TrimSpace(c.Region)
		}
		key := v.CustomerID + "\x1f" + v.ProductType
		cur, ok := out[key]
		if !ok || v.SortOrder < cur.sortOrder || (v.SortOrder == cur.sortOrder && v.VisitDate < cur.date) {
			out[key] = prevVisitRef{day: day, sortOrder: v.SortOrder, region: reg, date: v.VisitDate}
		}
	}
	return out
}

func dominantRegionByPrevDay(prev map[string]prevVisitRef) map[string]string {
	type hit struct {
		id, region string
	}
	hits := map[string][]hit{}
	for key, r := range prev {
		id := key
		if i := strings.IndexByte(key, 0x1f); i >= 0 {
			id = key[:i]
		}
		hits[r.date] = append(hits[r.date], hit{id: id, region: r.region})
	}
	out := map[string]string{}
	for date, list := range hits {
		ids := make([]string, 0, len(list))
		regs := map[string]string{}
		for _, h := range list {
			ids = append(ids, h.id)
			regs[h.id] = h.region
		}
		stats := model.CountRegionVisits(ids, func(id string) string { return regs[id] })
		out[date] = model.DominantRegion(stats)
	}
	return out
}

func mappedPrevDate(it generateSlot, prev map[string]prevVisitRef, year, month int, loc *time.Location, cal *Calendar) (string, int, bool) {
	if len(prev) == 0 {
		return "", 0, false
	}
	ref, ok := prev[slotPrevKey(it)]
	if !ok {
		return "", 0, false
	}
	last := time.Date(year, time.Month(month)+1, 0, 0, 0, 0, 0, loc).Day()
	d := ref.day
	if d > last {
		d = last
	}
	t := time.Date(year, time.Month(month), d, 0, 0, 0, 0, loc)
	ds := shiftFixedDateInMonth(cal, t.Format("2006-01-02"), year, month)
	if ds == "" {
		return "", 0, false
	}
	return ds, ref.sortOrder, true
}

func fixedDatesForMonth(year, month int, rule string, loc *time.Location, cal *Calendar) []string {
	days, lastMon := model.ParseFixedRule(rule)
	last := time.Date(year, time.Month(month)+1, 0, 0, 0, 0, 0, loc).Day()
	seen := map[string]bool{}
	var out []string
	add := func(d int) {
		if d < 1 || d > last {
			return
		}
		t := time.Date(year, time.Month(month), d, 0, 0, 0, 0, loc)
		ds := shiftFixedDateInMonth(cal, t.Format("2006-01-02"), year, month)
		if ds == "" || seen[ds] {
			return
		}
		seen[ds] = true
		out = append(out, ds)
	}
	for _, d := range days {
		add(d)
	}
	if lastMon {
		add(lastWeekdayOfMonth(year, month, time.Monday, loc))
	}
	return out
}

// shiftFixedDateInMonth 휴일이면 §23.13 NextWorkingDay. 달을 넘기면 같은 달 PrevWorkingDay.
func shiftFixedDateInMonth(cal *Calendar, date string, year, month int) string {
	if cal == nil {
		cal = NewCalendar(nil)
	}
	next := cal.NextWorkingDay(date)
	if next == "" {
		return ""
	}
	t, err := time.ParseInLocation("2006-01-02", next, time.Local)
	if err != nil {
		return ""
	}
	if t.Year() == year && int(t.Month()) == month {
		return next
	}
	prev := cal.PrevWorkingDay(date)
	if prev == "" {
		return ""
	}
	t2, err := time.ParseInLocation("2006-01-02", prev, time.Local)
	if err != nil || t2.Year() != year || int(t2.Month()) != month {
		return ""
	}
	return prev
}

func regionOrderMap(items []model.RegionDistanceOrder) map[string]int {
	out := map[string]int{}
	for _, it := range items {
		out[model.RegionKey(it.Sido, it.Sigungu)] = it.SortOrder
	}
	return out
}

func lookupDistanceRank(cfg model.MaintenanceSiteConfig, dist map[string]int, far bool) int {
	if len(dist) == 0 {
		return 1_000_000
	}
	var ranks []int
	add := func(sido, sigungu string) {
		if n, ok := dist[model.RegionKey(sido, sigungu)]; ok {
			ranks = append(ranks, n)
		}
	}
	add(cfg.AddrSido, cfg.AddrSigungu)
	add(cfg.AddrSido, "")
	reg := strings.TrimSpace(cfg.Region)
	if reg != "" {
		for k, n := range dist {
			parts := strings.SplitN(k, "\x1f", 2)
			if len(parts) == 2 && (parts[0] == reg || parts[1] == reg) {
				ranks = append(ranks, n)
			}
		}
	}
	if len(ranks) == 0 {
		return 1_000_000
	}
	sort.Ints(ranks)
	n := ranks[0]
	if far {
		return -n
	}
	return n
}

// UnregisteredRegionCount 순서표에 없는 시군구 수. 생성 확인 화면용. §34.4.3
func UnregisteredRegionCount(configs []model.MaintenanceSiteConfig, dist []model.RegionDistanceOrder) int {
	m := regionOrderMap(dist)
	seen := map[string]bool{}
	n := 0
	for _, c := range configs {
		key := strings.TrimSpace(c.AddrSido) + "\x1f" + strings.TrimSpace(c.AddrSigungu)
		if key == "\x1f" {
			key = "region\x1f" + strings.TrimSpace(c.Region)
		}
		if seen[key] {
			continue
		}
		seen[key] = true
		if lookupDistanceRank(c, m, false) >= 1_000_000 {
			n++
		}
	}
	return n
}

func insertGeneratedOrSkip(repo *repository.MaintenanceRepo, planID, date string, sortOrder int, it generateSlot) (skipped int, err error) {
	err = insertGeneratedVisit(repo, planID, date, sortOrder, it)
	if errors.Is(err, errMonthSkip) {
		return 1, nil
	}
	return 0, err
}

func insertGeneratedVisit(repo *repository.MaintenanceRepo, planID, date string, sortOrder int, it generateSlot) error {
	if dup, err := repo.MonthDuplicate(planID, it.cfg.CustomerID, it.slot.ProductType, date, ""); err != nil {
		return err
	} else if dup != nil {
		return errMonthSkip
	}
	cat := it.cfg.EntryCategory
	if cat == "" {
		if it.fixed {
			cat = "fixed"
		} else {
			cat = "normal"
		}
	}
	return repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID:        planID,
		VisitDate:     date,
		CustomerID:    it.cfg.CustomerID,
		SortOrder:     sortOrder,
		AutoGenerated: true,
		EntryCategory: cat,
		ProductType:   it.slot.ProductType,
		Assignee:      repo.AssigneeForVisit(planID, it.cfg.CustomerID, it.slot.ProductType, date),
	})
}

func dateAfterToday(ds, today string) bool {
	ds = strings.TrimSpace(ds)
	today = strings.TrimSpace(today)
	if ds == "" || today == "" {
		return true
	}
	return ds > today
}

func filterDatesAfterToday(dates []string, today string) []string {
	if today == "" {
		return dates
	}
	var out []string
	for _, d := range dates {
		if dateAfterToday(d, today) {
			out = append(out, d)
		}
	}
	return out
}

func nextOpenWorkday(workdays []string, dayCount map[string]int, perDay int) (string, bool) {
	if perDay < 1 {
		perDay = repository.DefaultMaintenanceAutoDailyLimit
	}
	for _, d := range workdays {
		if dayCount[d] < perDay {
			return d, true
		}
	}
	return "", false
}

func lastWeekdayOfMonth(year, month int, wd time.Weekday, loc *time.Location) int {
	last := time.Date(year, time.Month(month+1), 0, 0, 0, 0, 0, loc).Day()
	for d := last; d >= 1; d-- {
		t := time.Date(year, time.Month(month), d, 0, 0, 0, 0, loc)
		if t.Weekday() == wd {
			return d
		}
	}
	return 0
}

// workdaysBefore25 1~24일 근무일. 25일 이후는 쓰지 않는다.
func workdaysBefore25(year, month int, loc *time.Location, cal *Calendar) []string {
	if cal == nil {
		cal = NewCalendar(nil)
	}
	var out []string
	for d := 1; d <= 24; d++ {
		t := time.Date(year, time.Month(month), d, 0, 0, 0, 0, loc)
		ds := t.Format("2006-01-02")
		if !cal.IsWorkingDay(ds) {
			continue
		}
		out = append(out, ds)
	}
	return out
}

// workdaysForMonth 테스트 호환 별칭.
func workdaysForMonth(year, month int, loc *time.Location) []string {
	return workdaysBefore25(year, month, loc, nil)
}
