package service

import (
	"fmt"
	"sort"
	"time"

	"customer-support/internal/model"
	"customer-support/internal/repository"
)

const fixedRuleLastMonday = "LAST_MONDAY_OF_MONTH"

type generateSlot struct {
	cfg   model.MaintenanceSiteConfig
	slot  model.UnassignedMonthSlot
	fixed bool
}

// AutoGenerateMaintenance 기획서 §23.5 자동 초안.
// 주기 도래 사이트만, 점검대상별로 방문을 나누고(product_type 필수),
// 고정 규칙을 먼저 넣은 뒤 나머지를 지역순으로 25일 이전 평일에 나열한다.
// 하루 상한을 넘기거나 평일이 모자라면 넣지 않는다(「일정 배정안됨」).
func AutoGenerateMaintenance(repo *repository.MaintenanceRepo, planID string) error {
	plan, err := repo.GetPlan(planID)
	if err != nil || plan == nil {
		return fmt.Errorf("계획을 찾을 수 없습니다")
	}
	configs, err := repo.ListSiteConfigs()
	if err != nil {
		return err
	}
	if len(configs) == 0 {
		return fmt.Errorf("정기점검 사이트 설정이 없습니다. 먼저 「점검 사이트 설정」에서 등록하세요")
	}

	if _, _, err := repo.DeleteAutoVisits(planID); err != nil {
		return err
	}

	y := plan.PlanYear
	loc := time.Local
	perDay := repo.AutoGenerateDailyLimit()
	cal := NewCalendar(repo.Holidays())

	for m := 1; m <= 12; m++ {
		fixed, flex := dueSlotsForMonth(configs, m)
		existing, err := repo.ListVisitsByMonth(planID, y, m)
		if err != nil {
			return err
		}
		dayCount := map[string]int{}
		for _, v := range existing {
			dayCount[v.VisitDate]++
		}

		for _, it := range fixed {
			if repo.HasVisitInMonth(planID, it.cfg.CustomerID, y, m, it.slot.ProductType) {
				continue
			}
			day := lastWeekdayOfMonth(y, m, time.Monday, loc)
			if day == 0 {
				continue
			}
			t := time.Date(y, time.Month(m), day, 0, 0, 0, 0, loc)
			ds := t.Format("2006-01-02")
			if !cal.IsWorkingDay(ds) {
				continue
			}
			if err := insertGeneratedVisit(repo, planID, ds, dayCount[ds], it); err != nil {
				return err
			}
			dayCount[ds]++
		}

		workdays := workdaysBefore25(y, m, loc, cal)
		for _, it := range flex {
			if repo.HasVisitInMonth(planID, it.cfg.CustomerID, y, m, it.slot.ProductType) {
				continue
			}
			ds, ok := nextOpenWorkday(workdays, dayCount, perDay)
			if !ok {
				// 25일 이전 평일이 모자라면 넣지 않는다. 26일 이후로 밀어 넣지 않음.
				continue
			}
			if err := insertGeneratedVisit(repo, planID, ds, dayCount[ds], it); err != nil {
				return err
			}
			dayCount[ds]++
		}
	}

	repo.TouchPlanUpdated(planID)
	return nil
}

func dueSlotsForMonth(configs []model.MaintenanceSiteConfig, month int) (fixed, flex []generateSlot) {
	for _, c := range configs {
		slots := model.SiteDueProductSlots(c, month)
		isFixed := c.FixedRule == fixedRuleLastMonday
		for _, s := range slots {
			it := generateSlot{cfg: c, slot: s, fixed: isFixed}
			if isFixed {
				fixed = append(fixed, it)
			} else {
				flex = append(flex, it)
			}
		}
	}
	sortGenerateSlots(fixed)
	sortGenerateSlots(flex)
	return fixed, flex
}

func sortGenerateSlots(items []generateSlot) {
	sort.Slice(items, func(i, j int) bool {
		if items[i].cfg.Region != items[j].cfg.Region {
			return items[i].cfg.Region < items[j].cfg.Region
		}
		if items[i].cfg.ShortName != items[j].cfg.ShortName {
			return items[i].cfg.ShortName < items[j].cfg.ShortName
		}
		if items[i].cfg.CustomerID != items[j].cfg.CustomerID {
			return items[i].cfg.CustomerID < items[j].cfg.CustomerID
		}
		return items[i].slot.SlotKey < items[j].slot.SlotKey
	})
}

func insertGeneratedVisit(repo *repository.MaintenanceRepo, planID, date string, sortOrder int, it generateSlot) error {
	cat := it.cfg.EntryCategory
	if cat == "" {
		if it.fixed {
			cat = "fixed"
		} else {
			cat = "normal"
		}
	}
	return repo.InsertVisitFull(model.MaintenanceVisit{
		PlanID:        planID,
		VisitDate:     date,
		CustomerID:    it.cfg.CustomerID,
		SortOrder:     sortOrder,
		AutoGenerated: true,
		EntryCategory: cat,
		ProductType:   it.slot.ProductType,
		Assignee:      repo.AssigneeForVisit(planID, it.cfg.CustomerID, it.slot.ProductType, date),
	})
}

func nextOpenWorkday(workdays []string, dayCount map[string]int, perDay int) (string, bool) {
	if perDay < 1 {
		perDay = repository.DefaultMaintenanceAutoDailyLimit
	}
	for _, d := range workdays {
		if dayCount[d] < perDay {
			return d, true
		}
	}
	return "", false
}

func lastWeekdayOfMonth(year, month int, wd time.Weekday, loc *time.Location) int {
	last := time.Date(year, time.Month(month+1), 0, 0, 0, 0, 0, loc).Day()
	for d := last; d >= 1; d-- {
		t := time.Date(year, time.Month(month), d, 0, 0, 0, 0, loc)
		if t.Weekday() == wd {
			return d
		}
	}
	return 0
}

// workdaysBefore25 1~24일 근무일. 25일 이후는 쓰지 않는다.
func workdaysBefore25(year, month int, loc *time.Location, cal *Calendar) []string {
	if cal == nil {
		cal = NewCalendar(nil)
	}
	var out []string
	for d := 1; d <= 24; d++ {
		t := time.Date(year, time.Month(month), d, 0, 0, 0, 0, loc)
		ds := t.Format("2006-01-02")
		if !cal.IsWorkingDay(ds) {
			continue
		}
		out = append(out, ds)
	}
	return out
}

// workdaysForMonth 테스트 호환 별칭.
func workdaysForMonth(year, month int, loc *time.Location) []string {
	return workdaysBefore25(year, month, loc, nil)
}
